-- GOLD Layer | Fact: GOLD.FACT_RETURNS
-- Grain: one row per return request
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE FACT_RETURNS AS
SELECT
    r.RETURN_SK,
    TO_NUMBER(TO_CHAR(r.RETURN_DATE, 'YYYYMMDD'))   AS DATE_SK,
    c.CUSTOMER_SK,
    o.ORDER_SK,
    r.RETURN_ID,
    r.ORDER_ID,
    r.CUSTOMER_ID,
    r.RETURN_DATE,
    r.RETURN_REASON,
    r.RETURN_STATUS,
    r.REFUND_AMOUNT,
    r.REFUND_METHOD,
    r.ITEMS_COUNT,
    DATEDIFF('day', o.ORDER_DATE, r.RETURN_DATE)    AS DAYS_TO_RETURN,
    CURRENT_TIMESTAMP()                             AS DW_REFRESHED_AT
FROM SILVER.RETURNS r
LEFT JOIN SILVER.ORDERS       o ON r.ORDER_ID     = o.ORDER_ID
LEFT JOIN GOLD.DIM_CUSTOMERS  c ON r.CUSTOMER_ID  = c.CUSTOMER_ID AND c.IS_CURRENT = TRUE;
