-- GOLD Layer | Fact: GOLD.FACT_INVENTORY_SNAPSHOTS
-- Grain: one row per product per location per snapshot date
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE FACT_INVENTORY_SNAPSHOTS AS
SELECT
    i.INVENTORY_SK,
    TO_NUMBER(TO_CHAR(i.SNAPSHOT_DATE, 'YYYYMMDD'))  AS DATE_SK,
    p.PRODUCT_SK,
    s.SUPPLIER_SK,
    i.PRODUCT_ID,
    i.LOCATION_ID,
    i.LOCATION_TYPE,
    i.QUANTITY_ON_HAND,
    i.QUANTITY_RESERVED,
    i.QUANTITY_AVAILABLE,
    i.REORDER_POINT,
    i.REORDER_QUANTITY,
    i.SNAPSHOT_DATE,
    i.SNAPSHOT_TIMESTAMP,
    IFF(i.QUANTITY_AVAILABLE <= i.REORDER_POINT, TRUE, FALSE)        AS IS_BELOW_REORDER,
    IFF(i.QUANTITY_AVAILABLE = 0, TRUE, FALSE)                       AS IS_OUT_OF_STOCK,
    p.UNIT_COST * i.QUANTITY_ON_HAND                                 AS INVENTORY_VALUE,
    CURRENT_TIMESTAMP()                                              AS DW_REFRESHED_AT
FROM SILVER.INVENTORY i
LEFT JOIN GOLD.DIM_PRODUCTS  p ON i.PRODUCT_ID  = p.PRODUCT_ID
LEFT JOIN GOLD.DIM_SUPPLIERS s ON p.SUPPLIER_ID = s.SUPPLIER_ID;
