-- GOLD Layer | Fact: GOLD.FACT_WEB_SESSIONS
-- Grain: one row per web session
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE FACT_WEB_SESSIONS AS
SELECT
    ws.SESSION_SK,
    TO_NUMBER(TO_CHAR(DATE(ws.SESSION_START), 'YYYYMMDD'))  AS DATE_SK,
    c.CUSTOMER_SK,
    cam.CAMPAIGN_SK,
    ws.SESSION_ID,
    ws.CUSTOMER_ID,
    ws.DEVICE_TYPE,
    ws.BROWSER,
    ws.OS,
    ws.CHANNEL,
    ws.CAMPAIGN_ID,
    ws.SESSION_START,
    ws.SESSION_END,
    ws.SESSION_DURATION_SEC,
    ws.PAGE_VIEWS,
    ws.IS_BOUNCE,
    ws.CONVERTED,
    ws.ORDER_ID,
    ws.LANDING_PAGE,
    CURRENT_TIMESTAMP()                                     AS DW_REFRESHED_AT
FROM SILVER.WEB_SESSIONS ws
LEFT JOIN GOLD.DIM_CUSTOMERS  c   ON ws.CUSTOMER_ID  = c.CUSTOMER_ID AND c.IS_CURRENT = TRUE
LEFT JOIN GOLD.DIM_CAMPAIGNS  cam ON ws.CAMPAIGN_ID  = cam.CAMPAIGN_ID;
