-- GOLD Layer | Fact: GOLD.FACT_PAYMENTS
-- Grain: one row per payment transaction
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE FACT_PAYMENTS AS
SELECT
    p.PAYMENT_SK,
    TO_NUMBER(TO_CHAR(DATE(p.PAYMENT_TIMESTAMP), 'YYYYMMDD')) AS DATE_SK,
    c.CUSTOMER_SK,
    o.ORDER_SK,
    p.PAYMENT_ID,
    p.ORDER_ID,
    p.CUSTOMER_ID,
    p.PAYMENT_METHOD,
    p.PAYMENT_STATUS,
    p.AMOUNT,
    p.CURRENCY_CODE,
    p.PAYMENT_TIMESTAMP,
    p.IS_REFUND,
    p.ORIGINAL_PAYMENT_ID,
    CURRENT_TIMESTAMP()                                       AS DW_REFRESHED_AT
FROM SILVER.PAYMENTS p
LEFT JOIN SILVER.ORDERS       o ON p.ORDER_ID     = o.ORDER_ID
LEFT JOIN GOLD.DIM_CUSTOMERS  c ON p.CUSTOMER_ID  = c.CUSTOMER_ID AND c.IS_CURRENT = TRUE;
