-- GOLD Layer | Fact: GOLD.FACT_LOYALTY_TRANSACTIONS
-- Grain: one row per loyalty point earn/redeem event
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE FACT_LOYALTY_TRANSACTIONS AS
SELECT
    lp.LOYALTY_SK,
    TO_NUMBER(TO_CHAR(lp.TRANSACTION_DATE, 'YYYYMMDD'))  AS DATE_SK,
    c.CUSTOMER_SK,
    o.ORDER_SK,
    lp.TRANSACTION_ID,
    lp.CUSTOMER_ID,
    lp.ORDER_ID,
    lp.TRANSACTION_TYPE,
    lp.POINTS_CHANGE,
    lp.POINTS_BALANCE_AFTER,
    lp.TRANSACTION_DATE,
    lp.TRANSACTION_TIMESTAMP,
    lp.EXPIRY_DATE,
    lp.REFERENCE_CODE,
    CURRENT_TIMESTAMP()                                  AS DW_REFRESHED_AT
FROM SILVER.LOYALTY_POINTS lp
LEFT JOIN SILVER.ORDERS       o ON lp.ORDER_ID    = o.ORDER_ID
LEFT JOIN GOLD.DIM_CUSTOMERS  c ON lp.CUSTOMER_ID = c.CUSTOMER_ID AND c.IS_CURRENT = TRUE;
