-- GOLD Layer | Fact: GOLD.FACT_SHIPMENTS
-- Grain: one row per shipment
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE FACT_SHIPMENTS AS
SELECT
    sh.SHIPMENT_SK,
    TO_NUMBER(TO_CHAR(sh.SHIP_DATE, 'YYYYMMDD'))        AS SHIP_DATE_SK,
    TO_NUMBER(TO_CHAR(sh.ACTUAL_DELIVERY, 'YYYYMMDD'))  AS DELIVERY_DATE_SK,
    c.CUSTOMER_SK,
    o.ORDER_SK,
    sh.SHIPMENT_ID,
    sh.ORDER_ID,
    sh.CUSTOMER_ID,
    sh.CARRIER,
    sh.TRACKING_NUMBER,
    sh.SHIP_DATE,
    sh.ESTIMATED_DELIVERY,
    sh.ACTUAL_DELIVERY,
    sh.SHIPMENT_STATUS,
    sh.SHIPPING_METHOD,
    sh.DESTINATION_COUNTRY,
    sh.WEIGHT_KG,
    sh.SHIPPING_COST,
    sh.IS_LATE,
    sh.DAYS_TO_DELIVER,
    IFF(sh.ACTUAL_DELIVERY IS NOT NULL,
        DATEDIFF('day', sh.ESTIMATED_DELIVERY, sh.ACTUAL_DELIVERY),
        NULL)                                           AS DAYS_LATE,
    CURRENT_TIMESTAMP()                                 AS DW_REFRESHED_AT
FROM SILVER.SHIPMENTS sh
LEFT JOIN SILVER.ORDERS       o ON sh.ORDER_ID    = o.ORDER_ID
LEFT JOIN GOLD.DIM_CUSTOMERS  c ON sh.CUSTOMER_ID = c.CUSTOMER_ID AND c.IS_CURRENT = TRUE;
