-- GOLD Layer | Fact: GOLD.FACT_REVIEWS
-- Grain: one row per product review
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE FACT_REVIEWS AS
SELECT
    r.REVIEW_SK,
    TO_NUMBER(TO_CHAR(r.REVIEW_DATE, 'YYYYMMDD'))   AS DATE_SK,
    c.CUSTOMER_SK,
    p.PRODUCT_SK,
    o.ORDER_SK,
    r.REVIEW_ID,
    r.PRODUCT_ID,
    r.CUSTOMER_ID,
    r.ORDER_ID,
    r.RATING,
    r.REVIEW_DATE,
    r.IS_VERIFIED_PURCHASE,
    r.IS_FLAGGED,
    r.HELPFUL_VOTES,
    IFF(r.RATING >= 4, TRUE, FALSE)                 AS IS_POSITIVE,
    IFF(r.RATING <= 2, TRUE, FALSE)                 AS IS_NEGATIVE,
    CURRENT_TIMESTAMP()                             AS DW_REFRESHED_AT
FROM SILVER.REVIEWS r
LEFT JOIN GOLD.DIM_CUSTOMERS  c ON r.CUSTOMER_ID = c.CUSTOMER_ID AND c.IS_CURRENT = TRUE
LEFT JOIN GOLD.DIM_PRODUCTS   p ON r.PRODUCT_ID  = p.PRODUCT_ID
LEFT JOIN SILVER.ORDERS       o ON r.ORDER_ID    = o.ORDER_ID;
