-- GOLD Layer | Fact: GOLD.FACT_PROMOTIONS_USAGE
-- Grain: one row per order using a promotion
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE FACT_PROMOTIONS_USAGE AS
SELECT
    o.ORDER_SK,
    TO_NUMBER(TO_CHAR(o.ORDER_DATE, 'YYYYMMDD'))   AS DATE_SK,
    c.CUSTOMER_SK,
    promo.PROMOTION_SK,
    o.ORDER_ID,
    o.CUSTOMER_ID,
    o.PROMOTION_ID,
    promo.PROMOTION_TYPE,
    promo.DISCOUNT_VALUE,
    o.DISCOUNT_AMOUNT                              AS ACTUAL_DISCOUNT_GIVEN,
    o.SUBTOTAL_AMOUNT,
    o.TOTAL_AMOUNT,
    IFF(o.SUBTOTAL_AMOUNT > 0,
        o.DISCOUNT_AMOUNT / o.SUBTOTAL_AMOUNT * 100,
        NULL)                                      AS EFFECTIVE_DISCOUNT_PCT,
    o.ORDER_DATE,
    CURRENT_TIMESTAMP()                            AS DW_REFRESHED_AT
FROM SILVER.ORDERS o
JOIN  GOLD.DIM_PROMOTIONS promo ON o.PROMOTION_ID = promo.PROMOTION_ID
LEFT JOIN GOLD.DIM_CUSTOMERS  c ON o.CUSTOMER_ID  = c.CUSTOMER_ID AND c.IS_CURRENT = TRUE
WHERE o.PROMOTION_ID IS NOT NULL;
