-- GOLD Layer | Fact: GOLD.FACT_STORE_PERFORMANCE
-- Grain: one row per store per day
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE FACT_STORE_PERFORMANCE AS
SELECT
    s.STORE_SK,
    TO_NUMBER(TO_CHAR(o.ORDER_DATE, 'YYYYMMDD'))         AS DATE_SK,
    o.STORE_ID,
    o.ORDER_DATE,
    COUNT(DISTINCT o.ORDER_ID)                           AS ORDERS_COUNT,
    COUNT(DISTINCT o.CUSTOMER_ID)                        AS UNIQUE_CUSTOMERS,
    SUM(o.TOTAL_AMOUNT)                                  AS TOTAL_REVENUE,
    SUM(o.SUBTOTAL_AMOUNT)                               AS GROSS_REVENUE,
    SUM(o.DISCOUNT_AMOUNT)                               AS TOTAL_DISCOUNTS,
    SUM(o.TAX_AMOUNT)                                    AS TOTAL_TAX,
    AVG(o.TOTAL_AMOUNT)                                  AS AVG_ORDER_VALUE,
    COUNT(DISTINCT IFF(o.IS_FIRST_ORDER, o.CUSTOMER_ID, NULL)) AS NEW_CUSTOMERS,
    SUM(IFF(o.ORDER_STATUS = 'RETURNED', o.TOTAL_AMOUNT, 0))   AS RETURNED_REVENUE,
    CURRENT_TIMESTAMP()                                  AS DW_REFRESHED_AT
FROM SILVER.ORDERS o
LEFT JOIN GOLD.DIM_STORES s ON o.STORE_ID = s.STORE_ID
WHERE o.ORDER_STATUS NOT IN ('CANCELLED')
GROUP BY s.STORE_SK, o.STORE_ID, o.ORDER_DATE;
