-- SILVER Layer | Table: SILVER.ORDERS
-- Cleaned and typed from RAW.ORDERS
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_SK            NUMBER AUTOINCREMENT PRIMARY KEY,
    ORDER_ID            VARCHAR(50)    NOT NULL UNIQUE,
    CUSTOMER_ID         VARCHAR(50),
    STORE_ID            VARCHAR(50),
    ORDER_DATE          DATE,
    ORDER_TIMESTAMP     TIMESTAMP_NTZ,
    ORDER_STATUS        VARCHAR(30),   -- PENDING, CONFIRMED, SHIPPED, DELIVERED, CANCELLED, RETURNED
    CHANNEL             VARCHAR(20),   -- WEB, MOBILE, STORE, PHONE
    CURRENCY_CODE       VARCHAR(3)     DEFAULT 'USD',
    SUBTOTAL_AMOUNT     NUMBER(18,2),
    DISCOUNT_AMOUNT     NUMBER(18,2)   DEFAULT 0,
    TAX_AMOUNT          NUMBER(18,2)   DEFAULT 0,
    SHIPPING_AMOUNT     NUMBER(18,2)   DEFAULT 0,
    TOTAL_AMOUNT        NUMBER(18,2),
    PROMOTION_ID        VARCHAR(50),
    IS_FIRST_ORDER      BOOLEAN,
    SRC_LOAD_TIMESTAMP  TIMESTAMP_NTZ,
    DW_CREATED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATED_AT       TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP()
);

MERGE INTO SILVER.ORDERS tgt
USING (
    SELECT
        PAYLOAD:order_id::VARCHAR(50)                              AS ORDER_ID,
        PAYLOAD:customer_id::VARCHAR(50)                           AS CUSTOMER_ID,
        PAYLOAD:store_id::VARCHAR(50)                              AS STORE_ID,
        TRY_TO_DATE(PAYLOAD:order_date::VARCHAR)                   AS ORDER_DATE,
        TRY_TO_TIMESTAMP_NTZ(PAYLOAD:order_timestamp::VARCHAR)     AS ORDER_TIMESTAMP,
        UPPER(PAYLOAD:status::VARCHAR(30))                         AS ORDER_STATUS,
        UPPER(COALESCE(PAYLOAD:channel::VARCHAR(20), 'WEB'))       AS CHANNEL,
        COALESCE(PAYLOAD:currency::VARCHAR(3), 'USD')              AS CURRENCY_CODE,
        TRY_TO_DOUBLE(PAYLOAD:subtotal::VARCHAR)                   AS SUBTOTAL_AMOUNT,
        COALESCE(TRY_TO_DOUBLE(PAYLOAD:discount::VARCHAR), 0)      AS DISCOUNT_AMOUNT,
        COALESCE(TRY_TO_DOUBLE(PAYLOAD:tax::VARCHAR), 0)           AS TAX_AMOUNT,
        COALESCE(TRY_TO_DOUBLE(PAYLOAD:shipping::VARCHAR), 0)      AS SHIPPING_AMOUNT,
        TRY_TO_DOUBLE(PAYLOAD:total::VARCHAR)                      AS TOTAL_AMOUNT,
        PAYLOAD:promotion_id::VARCHAR(50)                          AS PROMOTION_ID,
        LOAD_TIMESTAMP                                             AS SRC_LOAD_TIMESTAMP,
        ROW_NUMBER() OVER (
            PARTITION BY PAYLOAD:order_id::VARCHAR
            ORDER BY LOAD_TIMESTAMP DESC
        )                                                          AS RN
    FROM RAW.ORDERS
    WHERE PAYLOAD:order_id IS NOT NULL
) src ON (tgt.ORDER_ID = src.ORDER_ID)
WHEN MATCHED AND src.RN = 1 THEN UPDATE SET
    tgt.ORDER_STATUS    = src.ORDER_STATUS,
    tgt.TOTAL_AMOUNT    = src.TOTAL_AMOUNT,
    tgt.DW_UPDATED_AT   = CURRENT_TIMESTAMP()
WHEN NOT MATCHED AND src.RN = 1 THEN INSERT (
    ORDER_ID, CUSTOMER_ID, STORE_ID, ORDER_DATE, ORDER_TIMESTAMP, ORDER_STATUS,
    CHANNEL, CURRENCY_CODE, SUBTOTAL_AMOUNT, DISCOUNT_AMOUNT, TAX_AMOUNT,
    SHIPPING_AMOUNT, TOTAL_AMOUNT, PROMOTION_ID, SRC_LOAD_TIMESTAMP
) VALUES (
    src.ORDER_ID, src.CUSTOMER_ID, src.STORE_ID, src.ORDER_DATE, src.ORDER_TIMESTAMP,
    src.ORDER_STATUS, src.CHANNEL, src.CURRENCY_CODE, src.SUBTOTAL_AMOUNT,
    src.DISCOUNT_AMOUNT, src.TAX_AMOUNT, src.SHIPPING_AMOUNT, src.TOTAL_AMOUNT,
    src.PROMOTION_ID, src.SRC_LOAD_TIMESTAMP
);
