-- SILVER Layer | Table: SILVER.ORDER_ITEMS
-- Cleaned order line items from RAW.ORDER_ITEMS
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ORDER_ITEM_SK       NUMBER AUTOINCREMENT PRIMARY KEY,
    ORDER_ID            VARCHAR(50)   NOT NULL,
    ITEM_ID             VARCHAR(50)   NOT NULL,
    PRODUCT_ID          VARCHAR(50),
    QUANTITY            NUMBER(10)    DEFAULT 1,
    UNIT_PRICE          NUMBER(18,4),
    DISCOUNT_AMOUNT     NUMBER(18,4)  DEFAULT 0,
    TAX_AMOUNT          NUMBER(18,4)  DEFAULT 0,
    LINE_TOTAL          NUMBER(18,4),
    RETURN_FLAG         BOOLEAN       DEFAULT FALSE,
    SRC_LOAD_TIMESTAMP  TIMESTAMP_NTZ,
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO SILVER.ORDER_ITEMS (
    ORDER_ID, ITEM_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE,
    DISCOUNT_AMOUNT, TAX_AMOUNT, LINE_TOTAL, RETURN_FLAG, SRC_LOAD_TIMESTAMP
)
SELECT
    PAYLOAD:order_id::VARCHAR(50),
    PAYLOAD:item_id::VARCHAR(50),
    PAYLOAD:product_id::VARCHAR(50),
    COALESCE(TRY_TO_NUMBER(PAYLOAD:quantity::VARCHAR), 1),
    TRY_TO_DOUBLE(PAYLOAD:unit_price::VARCHAR),
    COALESCE(TRY_TO_DOUBLE(PAYLOAD:discount::VARCHAR), 0),
    COALESCE(TRY_TO_DOUBLE(PAYLOAD:tax::VARCHAR), 0),
    TRY_TO_DOUBLE(PAYLOAD:line_total::VARCHAR),
    COALESCE(PAYLOAD:return_flag::BOOLEAN, FALSE),
    LOAD_TIMESTAMP
FROM RAW.ORDER_ITEMS
WHERE PAYLOAD:order_id IS NOT NULL
  AND PAYLOAD:item_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM SILVER.ORDER_ITEMS t
      WHERE t.ORDER_ID = PAYLOAD:order_id::VARCHAR
        AND t.ITEM_ID  = PAYLOAD:item_id::VARCHAR
  );
