-- SILVER Layer | Table: SILVER.PRODUCTS
-- Cleaned product catalog with SCD2
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_SK          NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID          VARCHAR(50)   NOT NULL,
    SKU                 VARCHAR(100),
    PRODUCT_NAME        VARCHAR(500),
    CATEGORY_ID         VARCHAR(50),
    SUPPLIER_ID         VARCHAR(50),
    BRAND               VARCHAR(200),
    UNIT_COST           NUMBER(18,4),
    UNIT_PRICE          NUMBER(18,4),
    WEIGHT_KG           NUMBER(10,4),
    IS_ACTIVE           BOOLEAN       DEFAULT TRUE,
    IS_DIGITAL          BOOLEAN       DEFAULT FALSE,
    -- SCD2
    EFFECTIVE_FROM      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EFFECTIVE_TO        TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ,
    IS_CURRENT          BOOLEAN       DEFAULT TRUE,
    SRC_LOAD_TIMESTAMP  TIMESTAMP_NTZ,
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

MERGE INTO SILVER.PRODUCTS tgt
USING (
    SELECT
        PAYLOAD:product_id::VARCHAR(50)     AS PRODUCT_ID,
        PAYLOAD:sku::VARCHAR(100)           AS SKU,
        TRIM(PAYLOAD:name::VARCHAR(500))    AS PRODUCT_NAME,
        PAYLOAD:category_id::VARCHAR(50)    AS CATEGORY_ID,
        PAYLOAD:supplier_id::VARCHAR(50)    AS SUPPLIER_ID,
        PAYLOAD:brand::VARCHAR(200)         AS BRAND,
        TRY_TO_DOUBLE(PAYLOAD:cost::VARCHAR)  AS UNIT_COST,
        TRY_TO_DOUBLE(PAYLOAD:price::VARCHAR) AS UNIT_PRICE,
        TRY_TO_DOUBLE(PAYLOAD:weight::VARCHAR) AS WEIGHT_KG,
        COALESCE(PAYLOAD:is_active::BOOLEAN, TRUE)   AS IS_ACTIVE,
        COALESCE(PAYLOAD:is_digital::BOOLEAN, FALSE)  AS IS_DIGITAL,
        LOAD_TIMESTAMP AS SRC_LOAD_TIMESTAMP,
        ROW_NUMBER() OVER (PARTITION BY PAYLOAD:product_id::VARCHAR ORDER BY LOAD_TIMESTAMP DESC) AS RN
    FROM RAW.PRODUCTS
    WHERE PAYLOAD:product_id IS NOT NULL
) src ON (tgt.PRODUCT_ID = src.PRODUCT_ID AND tgt.IS_CURRENT = TRUE AND src.RN = 1)
WHEN MATCHED AND (tgt.UNIT_PRICE != src.UNIT_PRICE OR tgt.IS_ACTIVE != src.IS_ACTIVE) THEN
    UPDATE SET tgt.IS_CURRENT = FALSE, tgt.EFFECTIVE_TO = CURRENT_TIMESTAMP(), tgt.DW_UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED AND src.RN = 1 THEN
    INSERT (PRODUCT_ID, SKU, PRODUCT_NAME, CATEGORY_ID, SUPPLIER_ID, BRAND, UNIT_COST, UNIT_PRICE, WEIGHT_KG, IS_ACTIVE, IS_DIGITAL, SRC_LOAD_TIMESTAMP)
    VALUES (src.PRODUCT_ID, src.SKU, src.PRODUCT_NAME, src.CATEGORY_ID, src.SUPPLIER_ID, src.BRAND, src.UNIT_COST, src.UNIT_PRICE, src.WEIGHT_KG, src.IS_ACTIVE, src.IS_DIGITAL, src.SRC_LOAD_TIMESTAMP);
