-- SILVER Layer | Table: SILVER.CATEGORIES
-- Product category hierarchy
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS CATEGORIES (
    CATEGORY_SK         NUMBER AUTOINCREMENT PRIMARY KEY,
    CATEGORY_ID         VARCHAR(50)   NOT NULL UNIQUE,
    CATEGORY_NAME       VARCHAR(200),
    PARENT_CATEGORY_ID  VARCHAR(50),
    CATEGORY_LEVEL      NUMBER(2),     -- 1=top, 2=sub, 3=leaf
    CATEGORY_PATH       VARCHAR(1000), -- e.g. "Electronics > Phones > Smartphones"
    IS_ACTIVE           BOOLEAN       DEFAULT TRUE,
    SRC_LOAD_TIMESTAMP  TIMESTAMP_NTZ,
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

MERGE INTO SILVER.CATEGORIES tgt
USING (
    SELECT
        PAYLOAD:category_id::VARCHAR(50)           AS CATEGORY_ID,
        TRIM(PAYLOAD:name::VARCHAR(200))            AS CATEGORY_NAME,
        PAYLOAD:parent_id::VARCHAR(50)              AS PARENT_CATEGORY_ID,
        TRY_TO_NUMBER(PAYLOAD:level::VARCHAR(2))    AS CATEGORY_LEVEL,
        PAYLOAD:path::VARCHAR(1000)                 AS CATEGORY_PATH,
        COALESCE(PAYLOAD:is_active::BOOLEAN, TRUE)  AS IS_ACTIVE,
        LOAD_TIMESTAMP                              AS SRC_LOAD_TIMESTAMP,
        ROW_NUMBER() OVER (PARTITION BY PAYLOAD:category_id::VARCHAR ORDER BY LOAD_TIMESTAMP DESC) AS RN
    FROM RAW.CATEGORIES
    WHERE PAYLOAD:category_id IS NOT NULL
) src ON (tgt.CATEGORY_ID = src.CATEGORY_ID AND src.RN = 1)
WHEN MATCHED THEN UPDATE SET
    tgt.CATEGORY_NAME      = src.CATEGORY_NAME,
    tgt.CATEGORY_PATH      = src.CATEGORY_PATH,
    tgt.IS_ACTIVE          = src.IS_ACTIVE,
    tgt.DW_UPDATED_AT      = CURRENT_TIMESTAMP()
WHEN NOT MATCHED AND src.RN = 1 THEN INSERT
    (CATEGORY_ID, CATEGORY_NAME, PARENT_CATEGORY_ID, CATEGORY_LEVEL, CATEGORY_PATH, IS_ACTIVE, SRC_LOAD_TIMESTAMP)
VALUES
    (src.CATEGORY_ID, src.CATEGORY_NAME, src.PARENT_CATEGORY_ID, src.CATEGORY_LEVEL, src.CATEGORY_PATH, src.IS_ACTIVE, src.SRC_LOAD_TIMESTAMP);
