-- SILVER Layer | Table: SILVER.SUPPLIERS
-- Cleaned supplier master data
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS SUPPLIERS (
    SUPPLIER_SK         NUMBER AUTOINCREMENT PRIMARY KEY,
    SUPPLIER_ID         VARCHAR(50)   NOT NULL UNIQUE,
    SUPPLIER_NAME       VARCHAR(300),
    CONTACT_NAME        VARCHAR(200),
    EMAIL               VARCHAR(254),
    PHONE               VARCHAR(20),
    COUNTRY             VARCHAR(100),
    REGION              VARCHAR(100),
    PAYMENT_TERMS_DAYS  NUMBER(3),
    LEAD_TIME_DAYS      NUMBER(3),
    IS_ACTIVE           BOOLEAN       DEFAULT TRUE,
    SUPPLIER_RATING     NUMBER(3,1),  -- 0.0 to 5.0
    SRC_LOAD_TIMESTAMP  TIMESTAMP_NTZ,
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

MERGE INTO SILVER.SUPPLIERS tgt
USING (
    SELECT
        PAYLOAD:supplier_id::VARCHAR(50)                       AS SUPPLIER_ID,
        TRIM(PAYLOAD:name::VARCHAR(300))                       AS SUPPLIER_NAME,
        TRIM(PAYLOAD:contact_name::VARCHAR(200))               AS CONTACT_NAME,
        LOWER(TRIM(PAYLOAD:email::VARCHAR(254)))               AS EMAIL,
        REGEXP_REPLACE(PAYLOAD:phone::VARCHAR, '[^0-9+]', '')  AS PHONE,
        PAYLOAD:country::VARCHAR(100)                          AS COUNTRY,
        PAYLOAD:region::VARCHAR(100)                           AS REGION,
        TRY_TO_NUMBER(PAYLOAD:payment_terms_days::VARCHAR)     AS PAYMENT_TERMS_DAYS,
        TRY_TO_NUMBER(PAYLOAD:lead_time_days::VARCHAR)         AS LEAD_TIME_DAYS,
        COALESCE(PAYLOAD:is_active::BOOLEAN, TRUE)             AS IS_ACTIVE,
        TRY_TO_DOUBLE(PAYLOAD:rating::VARCHAR)                 AS SUPPLIER_RATING,
        LOAD_TIMESTAMP                                         AS SRC_LOAD_TIMESTAMP,
        ROW_NUMBER() OVER (PARTITION BY PAYLOAD:supplier_id::VARCHAR ORDER BY LOAD_TIMESTAMP DESC) AS RN
    FROM RAW.SUPPLIERS
    WHERE PAYLOAD:supplier_id IS NOT NULL
) src ON (tgt.SUPPLIER_ID = src.SUPPLIER_ID AND src.RN = 1)
WHEN MATCHED THEN UPDATE SET
    tgt.SUPPLIER_NAME = src.SUPPLIER_NAME, tgt.SUPPLIER_RATING = src.SUPPLIER_RATING,
    tgt.IS_ACTIVE = src.IS_ACTIVE, tgt.DW_UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED AND src.RN = 1 THEN INSERT
    (SUPPLIER_ID, SUPPLIER_NAME, CONTACT_NAME, EMAIL, PHONE, COUNTRY, REGION, PAYMENT_TERMS_DAYS, LEAD_TIME_DAYS, IS_ACTIVE, SUPPLIER_RATING, SRC_LOAD_TIMESTAMP)
VALUES
    (src.SUPPLIER_ID, src.SUPPLIER_NAME, src.CONTACT_NAME, src.EMAIL, src.PHONE, src.COUNTRY, src.REGION, src.PAYMENT_TERMS_DAYS, src.LEAD_TIME_DAYS, src.IS_ACTIVE, src.SUPPLIER_RATING, src.SRC_LOAD_TIMESTAMP);
