-- SILVER Layer | Table: SILVER.INVENTORY
-- Current inventory levels per product per location
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS INVENTORY (
    INVENTORY_SK        NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID          VARCHAR(50)   NOT NULL,
    LOCATION_ID         VARCHAR(50)   NOT NULL,
    LOCATION_TYPE       VARCHAR(20),  -- WAREHOUSE, STORE, DC
    QUANTITY_ON_HAND    NUMBER(12),
    QUANTITY_RESERVED   NUMBER(12)    DEFAULT 0,
    QUANTITY_AVAILABLE  NUMBER(12),   -- computed: on_hand - reserved
    REORDER_POINT       NUMBER(12),
    REORDER_QUANTITY    NUMBER(12),
    SNAPSHOT_DATE       DATE,
    SNAPSHOT_TIMESTAMP  TIMESTAMP_NTZ,
    SRC_LOAD_TIMESTAMP  TIMESTAMP_NTZ,
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO SILVER.INVENTORY (
    PRODUCT_ID, LOCATION_ID, LOCATION_TYPE, QUANTITY_ON_HAND, QUANTITY_RESERVED,
    QUANTITY_AVAILABLE, REORDER_POINT, REORDER_QUANTITY, SNAPSHOT_DATE, SNAPSHOT_TIMESTAMP, SRC_LOAD_TIMESTAMP
)
SELECT
    PAYLOAD:product_id::VARCHAR(50),
    PAYLOAD:location_id::VARCHAR(50),
    UPPER(COALESCE(PAYLOAD:location_type::VARCHAR(20), 'WAREHOUSE')),
    COALESCE(TRY_TO_NUMBER(PAYLOAD:qty_on_hand::VARCHAR), 0),
    COALESCE(TRY_TO_NUMBER(PAYLOAD:qty_reserved::VARCHAR), 0),
    COALESCE(TRY_TO_NUMBER(PAYLOAD:qty_on_hand::VARCHAR), 0)
        - COALESCE(TRY_TO_NUMBER(PAYLOAD:qty_reserved::VARCHAR), 0),
    TRY_TO_NUMBER(PAYLOAD:reorder_point::VARCHAR),
    TRY_TO_NUMBER(PAYLOAD:reorder_qty::VARCHAR),
    TRY_TO_DATE(PAYLOAD:snapshot_date::VARCHAR),
    TRY_TO_TIMESTAMP_NTZ(PAYLOAD:snapshot_ts::VARCHAR),
    LOAD_TIMESTAMP
FROM RAW.INVENTORY
WHERE PAYLOAD:product_id IS NOT NULL AND PAYLOAD:location_id IS NOT NULL;
