-- SILVER Layer | Table: SILVER.PAYMENTS
-- Cleaned payment transactions
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS PAYMENTS (
    PAYMENT_SK          NUMBER AUTOINCREMENT PRIMARY KEY,
    PAYMENT_ID          VARCHAR(50)   NOT NULL UNIQUE,
    ORDER_ID            VARCHAR(50),
    CUSTOMER_ID         VARCHAR(50),
    PAYMENT_METHOD      VARCHAR(30),  -- CREDIT_CARD, DEBIT_CARD, PAYPAL, APPLE_PAY, BANK_TRANSFER
    PAYMENT_STATUS      VARCHAR(20),  -- PENDING, AUTHORIZED, CAPTURED, FAILED, REFUNDED
    AMOUNT              NUMBER(18,2),
    CURRENCY_CODE       VARCHAR(3)    DEFAULT 'USD',
    PAYMENT_TIMESTAMP   TIMESTAMP_NTZ,
    GATEWAY_REFERENCE   VARCHAR(200),
    IS_REFUND           BOOLEAN       DEFAULT FALSE,
    ORIGINAL_PAYMENT_ID VARCHAR(50),
    SRC_LOAD_TIMESTAMP  TIMESTAMP_NTZ,
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

MERGE INTO SILVER.PAYMENTS tgt
USING (
    SELECT
        PAYLOAD:payment_id::VARCHAR(50)                              AS PAYMENT_ID,
        PAYLOAD:order_id::VARCHAR(50)                                AS ORDER_ID,
        PAYLOAD:customer_id::VARCHAR(50)                             AS CUSTOMER_ID,
        UPPER(PAYLOAD:method::VARCHAR(30))                           AS PAYMENT_METHOD,
        UPPER(PAYLOAD:status::VARCHAR(20))                           AS PAYMENT_STATUS,
        TRY_TO_DOUBLE(PAYLOAD:amount::VARCHAR)                       AS AMOUNT,
        COALESCE(PAYLOAD:currency::VARCHAR(3), 'USD')                AS CURRENCY_CODE,
        TRY_TO_TIMESTAMP_NTZ(PAYLOAD:timestamp::VARCHAR)             AS PAYMENT_TIMESTAMP,
        PAYLOAD:gateway_ref::VARCHAR(200)                            AS GATEWAY_REFERENCE,
        COALESCE(PAYLOAD:is_refund::BOOLEAN, FALSE)                  AS IS_REFUND,
        PAYLOAD:original_payment_id::VARCHAR(50)                     AS ORIGINAL_PAYMENT_ID,
        LOAD_TIMESTAMP                                               AS SRC_LOAD_TIMESTAMP,
        ROW_NUMBER() OVER (PARTITION BY PAYLOAD:payment_id::VARCHAR ORDER BY LOAD_TIMESTAMP DESC) AS RN
    FROM RAW.PAYMENTS
    WHERE PAYLOAD:payment_id IS NOT NULL
) src ON (tgt.PAYMENT_ID = src.PAYMENT_ID AND src.RN = 1)
WHEN MATCHED THEN UPDATE SET tgt.PAYMENT_STATUS = src.PAYMENT_STATUS, tgt.DW_UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED AND src.RN = 1 THEN INSERT
    (PAYMENT_ID, ORDER_ID, CUSTOMER_ID, PAYMENT_METHOD, PAYMENT_STATUS, AMOUNT, CURRENCY_CODE, PAYMENT_TIMESTAMP, GATEWAY_REFERENCE, IS_REFUND, ORIGINAL_PAYMENT_ID, SRC_LOAD_TIMESTAMP)
VALUES
    (src.PAYMENT_ID, src.ORDER_ID, src.CUSTOMER_ID, src.PAYMENT_METHOD, src.PAYMENT_STATUS, src.AMOUNT, src.CURRENCY_CODE, src.PAYMENT_TIMESTAMP, src.GATEWAY_REFERENCE, src.IS_REFUND, src.ORIGINAL_PAYMENT_ID, src.SRC_LOAD_TIMESTAMP);
