-- SILVER Layer | Table: SILVER.RETURNS
-- Cleaned return and refund records
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS RETURNS (
    RETURN_SK           NUMBER AUTOINCREMENT PRIMARY KEY,
    RETURN_ID           VARCHAR(50)   NOT NULL UNIQUE,
    ORDER_ID            VARCHAR(50),
    CUSTOMER_ID         VARCHAR(50),
    RETURN_DATE         DATE,
    RETURN_REASON       VARCHAR(100), -- DEFECTIVE, WRONG_ITEM, NOT_AS_DESCRIBED, CHANGED_MIND, OTHER
    RETURN_STATUS       VARCHAR(30),  -- REQUESTED, APPROVED, RECEIVED, REFUNDED, REJECTED
    REFUND_AMOUNT       NUMBER(18,2),
    REFUND_METHOD       VARCHAR(30),
    ITEMS_COUNT         NUMBER(5),
    SRC_LOAD_TIMESTAMP  TIMESTAMP_NTZ,
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

MERGE INTO SILVER.RETURNS tgt
USING (
    SELECT
        PAYLOAD:return_id::VARCHAR(50)                          AS RETURN_ID,
        PAYLOAD:order_id::VARCHAR(50)                           AS ORDER_ID,
        PAYLOAD:customer_id::VARCHAR(50)                        AS CUSTOMER_ID,
        TRY_TO_DATE(PAYLOAD:return_date::VARCHAR)               AS RETURN_DATE,
        UPPER(COALESCE(PAYLOAD:reason::VARCHAR(100), 'OTHER'))  AS RETURN_REASON,
        UPPER(PAYLOAD:status::VARCHAR(30))                      AS RETURN_STATUS,
        TRY_TO_DOUBLE(PAYLOAD:refund_amount::VARCHAR)           AS REFUND_AMOUNT,
        UPPER(PAYLOAD:refund_method::VARCHAR(30))               AS REFUND_METHOD,
        TRY_TO_NUMBER(PAYLOAD:items_count::VARCHAR)             AS ITEMS_COUNT,
        LOAD_TIMESTAMP                                          AS SRC_LOAD_TIMESTAMP,
        ROW_NUMBER() OVER (PARTITION BY PAYLOAD:return_id::VARCHAR ORDER BY LOAD_TIMESTAMP DESC) AS RN
    FROM RAW.RETURNS
    WHERE PAYLOAD:return_id IS NOT NULL
) src ON (tgt.RETURN_ID = src.RETURN_ID AND src.RN = 1)
WHEN MATCHED THEN UPDATE SET tgt.RETURN_STATUS = src.RETURN_STATUS, tgt.REFUND_AMOUNT = src.REFUND_AMOUNT, tgt.DW_UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED AND src.RN = 1 THEN INSERT
    (RETURN_ID, ORDER_ID, CUSTOMER_ID, RETURN_DATE, RETURN_REASON, RETURN_STATUS, REFUND_AMOUNT, REFUND_METHOD, ITEMS_COUNT, SRC_LOAD_TIMESTAMP)
VALUES
    (src.RETURN_ID, src.ORDER_ID, src.CUSTOMER_ID, src.RETURN_DATE, src.RETURN_REASON, src.RETURN_STATUS, src.REFUND_AMOUNT, src.REFUND_METHOD, src.ITEMS_COUNT, src.SRC_LOAD_TIMESTAMP);
