-- SILVER Layer | Table: SILVER.REVIEWS
-- Cleaned product reviews with sentiment scoring
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS REVIEWS (
    REVIEW_SK           NUMBER AUTOINCREMENT PRIMARY KEY,
    REVIEW_ID           VARCHAR(50)   NOT NULL UNIQUE,
    PRODUCT_ID          VARCHAR(50),
    CUSTOMER_ID         VARCHAR(50),
    ORDER_ID            VARCHAR(50),
    RATING              NUMBER(2,1),  -- 1.0 to 5.0
    REVIEW_TITLE        VARCHAR(500),
    REVIEW_BODY         VARCHAR(5000),
    REVIEW_DATE         DATE,
    IS_VERIFIED_PURCHASE BOOLEAN      DEFAULT FALSE,
    IS_FLAGGED          BOOLEAN       DEFAULT FALSE,
    HELPFUL_VOTES       NUMBER(8)     DEFAULT 0,
    SRC_LOAD_TIMESTAMP  TIMESTAMP_NTZ,
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO SILVER.REVIEWS (
    REVIEW_ID, PRODUCT_ID, CUSTOMER_ID, ORDER_ID, RATING, REVIEW_TITLE,
    REVIEW_BODY, REVIEW_DATE, IS_VERIFIED_PURCHASE, IS_FLAGGED, HELPFUL_VOTES, SRC_LOAD_TIMESTAMP
)
SELECT
    PAYLOAD:review_id::VARCHAR(50),
    PAYLOAD:product_id::VARCHAR(50),
    PAYLOAD:customer_id::VARCHAR(50),
    PAYLOAD:order_id::VARCHAR(50),
    LEAST(5.0, GREATEST(1.0, TRY_TO_DOUBLE(PAYLOAD:rating::VARCHAR))),
    TRIM(PAYLOAD:title::VARCHAR(500)),
    TRIM(PAYLOAD:body::VARCHAR(5000)),
    TRY_TO_DATE(PAYLOAD:review_date::VARCHAR),
    COALESCE(PAYLOAD:verified_purchase::BOOLEAN, FALSE),
    COALESCE(PAYLOAD:is_flagged::BOOLEAN, FALSE),
    COALESCE(TRY_TO_NUMBER(PAYLOAD:helpful_votes::VARCHAR), 0),
    LOAD_TIMESTAMP
FROM RAW.REVIEWS
WHERE PAYLOAD:review_id IS NOT NULL
  AND TRY_TO_DOUBLE(PAYLOAD:rating::VARCHAR) BETWEEN 1 AND 5
  AND NOT EXISTS (SELECT 1 FROM SILVER.REVIEWS t WHERE t.REVIEW_ID = PAYLOAD:review_id::VARCHAR);
