-- SILVER Layer | Table: SILVER.EMPLOYEES
-- Cleaned employee records from HRIS
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS EMPLOYEES (
    EMPLOYEE_SK         NUMBER AUTOINCREMENT PRIMARY KEY,
    EMPLOYEE_ID         VARCHAR(50)   NOT NULL,
    FIRST_NAME          VARCHAR(100),
    LAST_NAME           VARCHAR(100),
    FULL_NAME           VARCHAR(200),
    JOB_TITLE           VARCHAR(200),
    DEPARTMENT          VARCHAR(100),
    STORE_ID            VARCHAR(50),
    MANAGER_ID          VARCHAR(50),
    HIRE_DATE           DATE,
    TERMINATION_DATE    DATE,
    EMPLOYMENT_STATUS   VARCHAR(20),  -- ACTIVE, TERMINATED, ON_LEAVE
    EMPLOYMENT_TYPE     VARCHAR(20),  -- FULL_TIME, PART_TIME, CONTRACT
    -- SCD2
    EFFECTIVE_FROM      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EFFECTIVE_TO        TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ,
    IS_CURRENT          BOOLEAN       DEFAULT TRUE,
    SRC_LOAD_TIMESTAMP  TIMESTAMP_NTZ,
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

MERGE INTO SILVER.EMPLOYEES tgt
USING (
    SELECT
        PAYLOAD:employee_id::VARCHAR(50)                              AS EMPLOYEE_ID,
        TRIM(PAYLOAD:first_name::VARCHAR(100))                        AS FIRST_NAME,
        TRIM(PAYLOAD:last_name::VARCHAR(100))                         AS LAST_NAME,
        TRIM(PAYLOAD:first_name::VARCHAR) || ' ' || TRIM(PAYLOAD:last_name::VARCHAR) AS FULL_NAME,
        PAYLOAD:job_title::VARCHAR(200)                               AS JOB_TITLE,
        PAYLOAD:department::VARCHAR(100)                              AS DEPARTMENT,
        PAYLOAD:store_id::VARCHAR(50)                                 AS STORE_ID,
        PAYLOAD:manager_id::VARCHAR(50)                               AS MANAGER_ID,
        TRY_TO_DATE(PAYLOAD:hire_date::VARCHAR)                       AS HIRE_DATE,
        TRY_TO_DATE(PAYLOAD:termination_date::VARCHAR)                AS TERMINATION_DATE,
        UPPER(COALESCE(PAYLOAD:status::VARCHAR(20), 'ACTIVE'))        AS EMPLOYMENT_STATUS,
        UPPER(COALESCE(PAYLOAD:employment_type::VARCHAR(20), 'FULL_TIME')) AS EMPLOYMENT_TYPE,
        LOAD_TIMESTAMP                                                AS SRC_LOAD_TIMESTAMP,
        ROW_NUMBER() OVER (PARTITION BY PAYLOAD:employee_id::VARCHAR ORDER BY LOAD_TIMESTAMP DESC) AS RN
    FROM RAW.EMPLOYEES
    WHERE PAYLOAD:employee_id IS NOT NULL
) src ON (tgt.EMPLOYEE_ID = src.EMPLOYEE_ID AND tgt.IS_CURRENT = TRUE AND src.RN = 1)
WHEN MATCHED AND (tgt.JOB_TITLE != src.JOB_TITLE OR tgt.STORE_ID != src.STORE_ID OR tgt.EMPLOYMENT_STATUS != src.EMPLOYMENT_STATUS) THEN
    UPDATE SET tgt.IS_CURRENT = FALSE, tgt.EFFECTIVE_TO = CURRENT_TIMESTAMP(), tgt.DW_UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED AND src.RN = 1 THEN INSERT
    (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, FULL_NAME, JOB_TITLE, DEPARTMENT, STORE_ID, MANAGER_ID, HIRE_DATE, TERMINATION_DATE, EMPLOYMENT_STATUS, EMPLOYMENT_TYPE, SRC_LOAD_TIMESTAMP)
VALUES
    (src.EMPLOYEE_ID, src.FIRST_NAME, src.LAST_NAME, src.FULL_NAME, src.JOB_TITLE, src.DEPARTMENT, src.STORE_ID, src.MANAGER_ID, src.HIRE_DATE, src.TERMINATION_DATE, src.EMPLOYMENT_STATUS, src.EMPLOYMENT_TYPE, src.SRC_LOAD_TIMESTAMP);
