-- SILVER Layer | Table: SILVER.PROMOTIONS
-- Cleaned promotions and discount rules
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS PROMOTIONS (
    PROMOTION_SK        NUMBER AUTOINCREMENT PRIMARY KEY,
    PROMOTION_ID        VARCHAR(50)   NOT NULL UNIQUE,
    PROMOTION_NAME      VARCHAR(300),
    PROMOTION_TYPE      VARCHAR(50),  -- PERCENTAGE_OFF, FIXED_AMOUNT, BUY_X_GET_Y, FREE_SHIPPING
    DISCOUNT_VALUE      NUMBER(10,4),
    MIN_ORDER_AMOUNT    NUMBER(18,2),
    MAX_DISCOUNT_AMOUNT NUMBER(18,2),
    START_DATE          DATE,
    END_DATE            DATE,
    APPLIES_TO          VARCHAR(30),  -- ALL, CATEGORY, PRODUCT, CUSTOMER_TIER
    PROMO_CODE          VARCHAR(50),
    IS_STACKABLE        BOOLEAN       DEFAULT FALSE,
    IS_ACTIVE           BOOLEAN       DEFAULT TRUE,
    USAGE_LIMIT         NUMBER(10),
    TIMES_USED          NUMBER(10)    DEFAULT 0,
    SRC_LOAD_TIMESTAMP  TIMESTAMP_NTZ,
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

MERGE INTO SILVER.PROMOTIONS tgt
USING (
    SELECT
        PAYLOAD:promotion_id::VARCHAR(50)                                 AS PROMOTION_ID,
        TRIM(PAYLOAD:name::VARCHAR(300))                                  AS PROMOTION_NAME,
        UPPER(PAYLOAD:type::VARCHAR(50))                                  AS PROMOTION_TYPE,
        TRY_TO_DOUBLE(PAYLOAD:discount_value::VARCHAR)                    AS DISCOUNT_VALUE,
        TRY_TO_DOUBLE(PAYLOAD:min_order_amount::VARCHAR)                  AS MIN_ORDER_AMOUNT,
        TRY_TO_DOUBLE(PAYLOAD:max_discount::VARCHAR)                      AS MAX_DISCOUNT_AMOUNT,
        TRY_TO_DATE(PAYLOAD:start_date::VARCHAR)                          AS START_DATE,
        TRY_TO_DATE(PAYLOAD:end_date::VARCHAR)                            AS END_DATE,
        UPPER(COALESCE(PAYLOAD:applies_to::VARCHAR(30), 'ALL'))           AS APPLIES_TO,
        UPPER(PAYLOAD:promo_code::VARCHAR(50))                            AS PROMO_CODE,
        COALESCE(PAYLOAD:is_stackable::BOOLEAN, FALSE)                    AS IS_STACKABLE,
        COALESCE(PAYLOAD:is_active::BOOLEAN, TRUE)                        AS IS_ACTIVE,
        TRY_TO_NUMBER(PAYLOAD:usage_limit::VARCHAR)                       AS USAGE_LIMIT,
        COALESCE(TRY_TO_NUMBER(PAYLOAD:times_used::VARCHAR), 0)           AS TIMES_USED,
        LOAD_TIMESTAMP                                                    AS SRC_LOAD_TIMESTAMP,
        ROW_NUMBER() OVER (PARTITION BY PAYLOAD:promotion_id::VARCHAR ORDER BY LOAD_TIMESTAMP DESC) AS RN
    FROM RAW.PROMOTIONS
    WHERE PAYLOAD:promotion_id IS NOT NULL
) src ON (tgt.PROMOTION_ID = src.PROMOTION_ID AND src.RN = 1)
WHEN MATCHED THEN UPDATE SET tgt.IS_ACTIVE = src.IS_ACTIVE, tgt.TIMES_USED = src.TIMES_USED, tgt.DW_UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED AND src.RN = 1 THEN INSERT
    (PROMOTION_ID, PROMOTION_NAME, PROMOTION_TYPE, DISCOUNT_VALUE, MIN_ORDER_AMOUNT, MAX_DISCOUNT_AMOUNT, START_DATE, END_DATE, APPLIES_TO, PROMO_CODE, IS_STACKABLE, IS_ACTIVE, USAGE_LIMIT, TIMES_USED, SRC_LOAD_TIMESTAMP)
VALUES
    (src.PROMOTION_ID, src.PROMOTION_NAME, src.PROMOTION_TYPE, src.DISCOUNT_VALUE, src.MIN_ORDER_AMOUNT, src.MAX_DISCOUNT_AMOUNT, src.START_DATE, src.END_DATE, src.APPLIES_TO, src.PROMO_CODE, src.IS_STACKABLE, src.IS_ACTIVE, src.USAGE_LIMIT, src.TIMES_USED, src.SRC_LOAD_TIMESTAMP);
