-- SILVER Layer | Table: SILVER.CAMPAIGNS
-- Cleaned marketing campaign data
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS CAMPAIGNS (
    CAMPAIGN_SK         NUMBER AUTOINCREMENT PRIMARY KEY,
    CAMPAIGN_ID         VARCHAR(50)   NOT NULL UNIQUE,
    CAMPAIGN_NAME       VARCHAR(300),
    CAMPAIGN_TYPE       VARCHAR(50),  -- EMAIL, SMS, SOCIAL, DISPLAY, SEARCH, AFFILIATE
    CHANNEL             VARCHAR(50),
    START_DATE          DATE,
    END_DATE            DATE,
    BUDGET_AMOUNT       NUMBER(18,2),
    SPEND_AMOUNT        NUMBER(18,2)  DEFAULT 0,
    TARGET_AUDIENCE     VARCHAR(100),
    IMPRESSIONS         NUMBER(18),
    CLICKS              NUMBER(18),
    CONVERSIONS         NUMBER(18),
    REVENUE_ATTRIBUTED  NUMBER(18,2),
    IS_ACTIVE           BOOLEAN       DEFAULT TRUE,
    SRC_LOAD_TIMESTAMP  TIMESTAMP_NTZ,
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

MERGE INTO SILVER.CAMPAIGNS tgt
USING (
    SELECT
        PAYLOAD:campaign_id::VARCHAR(50)                             AS CAMPAIGN_ID,
        TRIM(PAYLOAD:name::VARCHAR(300))                             AS CAMPAIGN_NAME,
        UPPER(PAYLOAD:type::VARCHAR(50))                             AS CAMPAIGN_TYPE,
        UPPER(PAYLOAD:channel::VARCHAR(50))                          AS CHANNEL,
        TRY_TO_DATE(PAYLOAD:start_date::VARCHAR)                     AS START_DATE,
        TRY_TO_DATE(PAYLOAD:end_date::VARCHAR)                       AS END_DATE,
        TRY_TO_DOUBLE(PAYLOAD:budget::VARCHAR)                       AS BUDGET_AMOUNT,
        COALESCE(TRY_TO_DOUBLE(PAYLOAD:spend::VARCHAR), 0)           AS SPEND_AMOUNT,
        PAYLOAD:target_audience::VARCHAR(100)                        AS TARGET_AUDIENCE,
        COALESCE(TRY_TO_NUMBER(PAYLOAD:impressions::VARCHAR), 0)     AS IMPRESSIONS,
        COALESCE(TRY_TO_NUMBER(PAYLOAD:clicks::VARCHAR), 0)          AS CLICKS,
        COALESCE(TRY_TO_NUMBER(PAYLOAD:conversions::VARCHAR), 0)     AS CONVERSIONS,
        COALESCE(TRY_TO_DOUBLE(PAYLOAD:revenue_attributed::VARCHAR), 0) AS REVENUE_ATTRIBUTED,
        COALESCE(PAYLOAD:is_active::BOOLEAN, TRUE)                   AS IS_ACTIVE,
        LOAD_TIMESTAMP                                               AS SRC_LOAD_TIMESTAMP,
        ROW_NUMBER() OVER (PARTITION BY PAYLOAD:campaign_id::VARCHAR ORDER BY LOAD_TIMESTAMP DESC) AS RN
    FROM RAW.CAMPAIGNS
    WHERE PAYLOAD:campaign_id IS NOT NULL
) src ON (tgt.CAMPAIGN_ID = src.CAMPAIGN_ID AND src.RN = 1)
WHEN MATCHED THEN UPDATE SET
    tgt.SPEND_AMOUNT = src.SPEND_AMOUNT, tgt.IMPRESSIONS = src.IMPRESSIONS,
    tgt.CLICKS = src.CLICKS, tgt.CONVERSIONS = src.CONVERSIONS,
    tgt.REVENUE_ATTRIBUTED = src.REVENUE_ATTRIBUTED, tgt.DW_UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED AND src.RN = 1 THEN INSERT
    (CAMPAIGN_ID, CAMPAIGN_NAME, CAMPAIGN_TYPE, CHANNEL, START_DATE, END_DATE, BUDGET_AMOUNT, SPEND_AMOUNT, TARGET_AUDIENCE, IMPRESSIONS, CLICKS, CONVERSIONS, REVENUE_ATTRIBUTED, IS_ACTIVE, SRC_LOAD_TIMESTAMP)
VALUES
    (src.CAMPAIGN_ID, src.CAMPAIGN_NAME, src.CAMPAIGN_TYPE, src.CHANNEL, src.START_DATE, src.END_DATE, src.BUDGET_AMOUNT, src.SPEND_AMOUNT, src.TARGET_AUDIENCE, src.IMPRESSIONS, src.CLICKS, src.CONVERSIONS, src.REVENUE_ATTRIBUTED, src.IS_ACTIVE, src.SRC_LOAD_TIMESTAMP);
