-- SILVER Layer | Table: SILVER.WEB_SESSIONS
-- Cleaned and sessionized web analytics
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS WEB_SESSIONS (
    SESSION_SK          NUMBER AUTOINCREMENT PRIMARY KEY,
    SESSION_ID          VARCHAR(100)  NOT NULL UNIQUE,
    CUSTOMER_ID         VARCHAR(50),
    DEVICE_TYPE         VARCHAR(20),  -- DESKTOP, MOBILE, TABLET
    BROWSER             VARCHAR(50),
    OS                  VARCHAR(50),
    CHANNEL             VARCHAR(30),  -- ORGANIC, PAID, EMAIL, DIRECT, REFERRAL, SOCIAL
    CAMPAIGN_ID         VARCHAR(50),
    SESSION_START       TIMESTAMP_NTZ,
    SESSION_END         TIMESTAMP_NTZ,
    SESSION_DURATION_SEC NUMBER(10),
    PAGE_VIEWS          NUMBER(8),
    IS_BOUNCE           BOOLEAN       DEFAULT FALSE,
    CONVERTED           BOOLEAN       DEFAULT FALSE,
    ORDER_ID            VARCHAR(50),
    LANDING_PAGE        VARCHAR(2000),
    SRC_LOAD_TIMESTAMP  TIMESTAMP_NTZ,
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO SILVER.WEB_SESSIONS (
    SESSION_ID, CUSTOMER_ID, DEVICE_TYPE, BROWSER, OS, CHANNEL, CAMPAIGN_ID,
    SESSION_START, SESSION_END, SESSION_DURATION_SEC, PAGE_VIEWS, IS_BOUNCE,
    CONVERTED, ORDER_ID, LANDING_PAGE, SRC_LOAD_TIMESTAMP
)
SELECT
    PAYLOAD:session_id::VARCHAR(100),
    PAYLOAD:customer_id::VARCHAR(50),
    UPPER(PAYLOAD:device_type::VARCHAR(20)),
    PAYLOAD:browser::VARCHAR(50),
    PAYLOAD:os::VARCHAR(50),
    UPPER(COALESCE(PAYLOAD:channel::VARCHAR(30), 'DIRECT')),
    PAYLOAD:campaign_id::VARCHAR(50),
    TRY_TO_TIMESTAMP_NTZ(PAYLOAD:session_start::VARCHAR),
    TRY_TO_TIMESTAMP_NTZ(PAYLOAD:session_end::VARCHAR),
    TRY_TO_NUMBER(PAYLOAD:duration_sec::VARCHAR),
    COALESCE(TRY_TO_NUMBER(PAYLOAD:page_views::VARCHAR), 1),
    COALESCE(PAYLOAD:is_bounce::BOOLEAN, FALSE),
    COALESCE(PAYLOAD:converted::BOOLEAN, FALSE),
    PAYLOAD:order_id::VARCHAR(50),
    PAYLOAD:landing_page::VARCHAR(2000),
    LOAD_TIMESTAMP
FROM RAW.WEB_SESSIONS
WHERE PAYLOAD:session_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM SILVER.WEB_SESSIONS t WHERE t.SESSION_ID = PAYLOAD:session_id::VARCHAR);
