-- SILVER Layer | Table: SILVER.SHIPMENTS
-- Cleaned shipment and tracking data
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS SHIPMENTS (
    SHIPMENT_SK          NUMBER AUTOINCREMENT PRIMARY KEY,
    SHIPMENT_ID          VARCHAR(50)  NOT NULL UNIQUE,
    ORDER_ID             VARCHAR(50),
    CUSTOMER_ID          VARCHAR(50),
    CARRIER              VARCHAR(50), -- FEDEX, UPS, DHL, USPS, LOCAL
    TRACKING_NUMBER      VARCHAR(100),
    SHIP_DATE            DATE,
    ESTIMATED_DELIVERY   DATE,
    ACTUAL_DELIVERY      DATE,
    SHIPMENT_STATUS      VARCHAR(30), -- LABEL_CREATED, PICKED_UP, IN_TRANSIT, OUT_FOR_DELIVERY, DELIVERED, EXCEPTION
    SHIPPING_METHOD      VARCHAR(50), -- STANDARD, EXPRESS, OVERNIGHT, SAME_DAY
    ORIGIN_ZIP           VARCHAR(20),
    DESTINATION_ZIP      VARCHAR(20),
    DESTINATION_COUNTRY  VARCHAR(2),
    WEIGHT_KG            NUMBER(10,4),
    SHIPPING_COST        NUMBER(18,2),
    IS_LATE              BOOLEAN,     -- actual_delivery > estimated_delivery
    DAYS_TO_DELIVER      NUMBER(5),
    SRC_LOAD_TIMESTAMP   TIMESTAMP_NTZ,
    DW_CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

MERGE INTO SILVER.SHIPMENTS tgt
USING (
    SELECT
        PAYLOAD:shipment_id::VARCHAR(50)                                  AS SHIPMENT_ID,
        PAYLOAD:order_id::VARCHAR(50)                                     AS ORDER_ID,
        PAYLOAD:customer_id::VARCHAR(50)                                  AS CUSTOMER_ID,
        UPPER(PAYLOAD:carrier::VARCHAR(50))                               AS CARRIER,
        PAYLOAD:tracking_number::VARCHAR(100)                             AS TRACKING_NUMBER,
        TRY_TO_DATE(PAYLOAD:ship_date::VARCHAR)                           AS SHIP_DATE,
        TRY_TO_DATE(PAYLOAD:estimated_delivery::VARCHAR)                  AS ESTIMATED_DELIVERY,
        TRY_TO_DATE(PAYLOAD:actual_delivery::VARCHAR)                     AS ACTUAL_DELIVERY,
        UPPER(PAYLOAD:status::VARCHAR(30))                                AS SHIPMENT_STATUS,
        UPPER(COALESCE(PAYLOAD:shipping_method::VARCHAR(50), 'STANDARD')) AS SHIPPING_METHOD,
        PAYLOAD:origin_zip::VARCHAR(20)                                   AS ORIGIN_ZIP,
        PAYLOAD:destination_zip::VARCHAR(20)                              AS DESTINATION_ZIP,
        UPPER(PAYLOAD:destination_country::VARCHAR(2))                    AS DESTINATION_COUNTRY,
        TRY_TO_DOUBLE(PAYLOAD:weight_kg::VARCHAR)                         AS WEIGHT_KG,
        TRY_TO_DOUBLE(PAYLOAD:shipping_cost::VARCHAR)                     AS SHIPPING_COST,
        LOAD_TIMESTAMP                                                    AS SRC_LOAD_TIMESTAMP,
        ROW_NUMBER() OVER (PARTITION BY PAYLOAD:shipment_id::VARCHAR ORDER BY LOAD_TIMESTAMP DESC) AS RN
    FROM RAW.SHIPMENTS
    WHERE PAYLOAD:shipment_id IS NOT NULL
) src ON (tgt.SHIPMENT_ID = src.SHIPMENT_ID AND src.RN = 1)
WHEN MATCHED THEN UPDATE SET
    tgt.SHIPMENT_STATUS = src.SHIPMENT_STATUS,
    tgt.ACTUAL_DELIVERY = src.ACTUAL_DELIVERY,
    tgt.IS_LATE         = IFF(src.ACTUAL_DELIVERY > src.ESTIMATED_DELIVERY, TRUE, FALSE),
    tgt.DAYS_TO_DELIVER = DATEDIFF('day', src.SHIP_DATE, src.ACTUAL_DELIVERY),
    tgt.DW_UPDATED_AT   = CURRENT_TIMESTAMP()
WHEN NOT MATCHED AND src.RN = 1 THEN INSERT
    (SHIPMENT_ID, ORDER_ID, CUSTOMER_ID, CARRIER, TRACKING_NUMBER, SHIP_DATE, ESTIMATED_DELIVERY, ACTUAL_DELIVERY, SHIPMENT_STATUS, SHIPPING_METHOD, ORIGIN_ZIP, DESTINATION_ZIP, DESTINATION_COUNTRY, WEIGHT_KG, SHIPPING_COST, IS_LATE, DAYS_TO_DELIVER, SRC_LOAD_TIMESTAMP)
VALUES
    (src.SHIPMENT_ID, src.ORDER_ID, src.CUSTOMER_ID, src.CARRIER, src.TRACKING_NUMBER, src.SHIP_DATE, src.ESTIMATED_DELIVERY, src.ACTUAL_DELIVERY, src.SHIPMENT_STATUS, src.SHIPPING_METHOD, src.ORIGIN_ZIP, src.DESTINATION_ZIP, src.DESTINATION_COUNTRY, src.WEIGHT_KG, src.SHIPPING_COST,
     IFF(src.ACTUAL_DELIVERY > src.ESTIMATED_DELIVERY, TRUE, FALSE),
     DATEDIFF('day', src.SHIP_DATE, src.ACTUAL_DELIVERY),
     src.SRC_LOAD_TIMESTAMP);
