-- SILVER Layer | Table: SILVER.ADDRESSES
-- Standardized and geocoded customer addresses
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS ADDRESSES (
    ADDRESS_SK          NUMBER AUTOINCREMENT PRIMARY KEY,
    ADDRESS_ID          VARCHAR(50)   NOT NULL,
    CUSTOMER_ID         VARCHAR(50),
    ADDRESS_TYPE        VARCHAR(20),  -- BILLING, SHIPPING, BOTH
    ADDRESS_LINE1       VARCHAR(300),
    ADDRESS_LINE2       VARCHAR(300),
    CITY                VARCHAR(100),
    STATE_PROVINCE      VARCHAR(100),
    POSTAL_CODE         VARCHAR(20),
    COUNTRY_CODE        VARCHAR(2),
    IS_DEFAULT          BOOLEAN       DEFAULT FALSE,
    IS_VALIDATED        BOOLEAN       DEFAULT FALSE,
    LATITUDE            FLOAT,
    LONGITUDE           FLOAT,
    -- SCD2
    EFFECTIVE_FROM      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EFFECTIVE_TO        TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ,
    IS_CURRENT          BOOLEAN       DEFAULT TRUE,
    SRC_LOAD_TIMESTAMP  TIMESTAMP_NTZ,
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

MERGE INTO SILVER.ADDRESSES tgt
USING (
    SELECT
        PAYLOAD:address_id::VARCHAR(50)                               AS ADDRESS_ID,
        PAYLOAD:customer_id::VARCHAR(50)                              AS CUSTOMER_ID,
        UPPER(COALESCE(PAYLOAD:type::VARCHAR(20), 'SHIPPING'))        AS ADDRESS_TYPE,
        TRIM(PAYLOAD:line1::VARCHAR(300))                             AS ADDRESS_LINE1,
        TRIM(PAYLOAD:line2::VARCHAR(300))                             AS ADDRESS_LINE2,
        TRIM(PAYLOAD:city::VARCHAR(100))                              AS CITY,
        TRIM(PAYLOAD:state::VARCHAR(100))                             AS STATE_PROVINCE,
        TRIM(PAYLOAD:postal_code::VARCHAR(20))                        AS POSTAL_CODE,
        UPPER(TRIM(PAYLOAD:country_code::VARCHAR(2)))                 AS COUNTRY_CODE,
        COALESCE(PAYLOAD:is_default::BOOLEAN, FALSE)                  AS IS_DEFAULT,
        COALESCE(PAYLOAD:is_validated::BOOLEAN, FALSE)                AS IS_VALIDATED,
        TRY_TO_DOUBLE(PAYLOAD:lat::VARCHAR)                           AS LATITUDE,
        TRY_TO_DOUBLE(PAYLOAD:lon::VARCHAR)                           AS LONGITUDE,
        LOAD_TIMESTAMP                                                AS SRC_LOAD_TIMESTAMP,
        ROW_NUMBER() OVER (PARTITION BY PAYLOAD:address_id::VARCHAR ORDER BY LOAD_TIMESTAMP DESC) AS RN
    FROM RAW.ADDRESSES
    WHERE PAYLOAD:address_id IS NOT NULL
) src ON (tgt.ADDRESS_ID = src.ADDRESS_ID AND tgt.IS_CURRENT = TRUE AND src.RN = 1)
WHEN MATCHED AND (tgt.ADDRESS_LINE1 != src.ADDRESS_LINE1 OR tgt.POSTAL_CODE != src.POSTAL_CODE) THEN
    UPDATE SET tgt.IS_CURRENT = FALSE, tgt.EFFECTIVE_TO = CURRENT_TIMESTAMP()
WHEN NOT MATCHED AND src.RN = 1 THEN INSERT
    (ADDRESS_ID, CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE_PROVINCE, POSTAL_CODE, COUNTRY_CODE, IS_DEFAULT, IS_VALIDATED, LATITUDE, LONGITUDE, SRC_LOAD_TIMESTAMP)
VALUES
    (src.ADDRESS_ID, src.CUSTOMER_ID, src.ADDRESS_TYPE, src.ADDRESS_LINE1, src.ADDRESS_LINE2, src.CITY, src.STATE_PROVINCE, src.POSTAL_CODE, src.COUNTRY_CODE, src.IS_DEFAULT, src.IS_VALIDATED, src.LATITUDE, src.LONGITUDE, src.SRC_LOAD_TIMESTAMP);
