-- SILVER Layer | Table: SILVER.LOYALTY_POINTS
-- Cleaned loyalty point earn/redeem transactions
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS LOYALTY_POINTS (
    LOYALTY_SK           NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID       VARCHAR(50)  NOT NULL UNIQUE,
    CUSTOMER_ID          VARCHAR(50),
    ORDER_ID             VARCHAR(50),
    TRANSACTION_TYPE     VARCHAR(20), -- EARN, REDEEM, EXPIRE, ADJUST, BONUS
    POINTS_CHANGE        NUMBER(12),  -- positive=earn/bonus, negative=redeem/expire
    POINTS_BALANCE_AFTER NUMBER(12),
    TRANSACTION_DATE     DATE,
    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ,
    EXPIRY_DATE          DATE,
    REFERENCE_CODE       VARCHAR(100),
    NOTES                VARCHAR(500),
    SRC_LOAD_TIMESTAMP   TIMESTAMP_NTZ,
    DW_CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO SILVER.LOYALTY_POINTS (
    TRANSACTION_ID, CUSTOMER_ID, ORDER_ID, TRANSACTION_TYPE, POINTS_CHANGE,
    POINTS_BALANCE_AFTER, TRANSACTION_DATE, TRANSACTION_TIMESTAMP,
    EXPIRY_DATE, REFERENCE_CODE, NOTES, SRC_LOAD_TIMESTAMP
)
SELECT
    PAYLOAD:transaction_id::VARCHAR(50),
    PAYLOAD:customer_id::VARCHAR(50),
    PAYLOAD:order_id::VARCHAR(50),
    UPPER(COALESCE(PAYLOAD:type::VARCHAR(20), 'EARN')),
    TRY_TO_NUMBER(PAYLOAD:points_change::VARCHAR),
    TRY_TO_NUMBER(PAYLOAD:balance_after::VARCHAR),
    TRY_TO_DATE(PAYLOAD:transaction_date::VARCHAR),
    TRY_TO_TIMESTAMP_NTZ(PAYLOAD:transaction_timestamp::VARCHAR),
    TRY_TO_DATE(PAYLOAD:expiry_date::VARCHAR),
    PAYLOAD:reference_code::VARCHAR(100),
    PAYLOAD:notes::VARCHAR(500),
    LOAD_TIMESTAMP
FROM RAW.LOYALTY_POINTS
WHERE PAYLOAD:transaction_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM SILVER.LOYALTY_POINTS t WHERE t.TRANSACTION_ID = PAYLOAD:transaction_id::VARCHAR);
