-- SILVER Layer | Table: SILVER.CUSTOMER_SEGMENTS
-- Derived customer segments based on RFM and behavior (computed from silver tables)
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS CUSTOMER_SEGMENTS (
    SEGMENT_SK          NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID         VARCHAR(50)   NOT NULL,
    SEGMENT_DATE        DATE          NOT NULL,
    -- RFM scores
    RECENCY_DAYS        NUMBER(6),
    FREQUENCY_ORDERS    NUMBER(8),
    MONETARY_TOTAL      NUMBER(18,2),
    RFM_RECENCY_SCORE   NUMBER(1),    -- 1-5 (5=best)
    RFM_FREQUENCY_SCORE NUMBER(1),
    RFM_MONETARY_SCORE  NUMBER(1),
    RFM_COMBINED_SCORE  VARCHAR(3),   -- e.g. "555", "111"
    -- Segment labels
    LIFECYCLE_SEGMENT   VARCHAR(50),  -- CHAMPION, LOYAL, AT_RISK, LOST, NEW, POTENTIAL
    VALUE_SEGMENT       VARCHAR(20),  -- HIGH, MEDIUM, LOW
    CHANNEL_PREFERENCE  VARCHAR(20),  -- WEB, MOBILE, STORE
    -- Flags
    IS_VIP              BOOLEAN       DEFAULT FALSE,
    HAS_CHURNED         BOOLEAN       DEFAULT FALSE,
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT pk_cust_seg UNIQUE (CUSTOMER_ID, SEGMENT_DATE)
);

-- Recompute RFM segments daily (replace today's snapshot)
DELETE FROM SILVER.CUSTOMER_SEGMENTS WHERE SEGMENT_DATE = CURRENT_DATE();

INSERT INTO SILVER.CUSTOMER_SEGMENTS (
    CUSTOMER_ID, SEGMENT_DATE, RECENCY_DAYS, FREQUENCY_ORDERS, MONETARY_TOTAL,
    RFM_RECENCY_SCORE, RFM_FREQUENCY_SCORE, RFM_MONETARY_SCORE, RFM_COMBINED_SCORE,
    LIFECYCLE_SEGMENT, VALUE_SEGMENT, IS_VIP, HAS_CHURNED
)
WITH rfm AS (
    SELECT
        CUSTOMER_ID,
        DATEDIFF('day', MAX(ORDER_DATE), CURRENT_DATE())       AS RECENCY_DAYS,
        COUNT(*)                                               AS FREQUENCY_ORDERS,
        SUM(TOTAL_AMOUNT)                                      AS MONETARY_TOTAL
    FROM SILVER.ORDERS
    WHERE ORDER_STATUS NOT IN ('CANCELLED', 'RETURNED')
    GROUP BY CUSTOMER_ID
),
scored AS (
    SELECT *,
        NTILE(5) OVER (ORDER BY RECENCY_DAYS DESC)   AS R_SCORE,
        NTILE(5) OVER (ORDER BY FREQUENCY_ORDERS)     AS F_SCORE,
        NTILE(5) OVER (ORDER BY MONETARY_TOTAL)       AS M_SCORE
    FROM rfm
)
SELECT
    CUSTOMER_ID,
    CURRENT_DATE()                                               AS SEGMENT_DATE,
    RECENCY_DAYS,
    FREQUENCY_ORDERS,
    MONETARY_TOTAL,
    R_SCORE,
    F_SCORE,
    M_SCORE,
    R_SCORE::VARCHAR || F_SCORE::VARCHAR || M_SCORE::VARCHAR     AS RFM_COMBINED_SCORE,
    CASE
        WHEN R_SCORE >= 4 AND F_SCORE >= 4 AND M_SCORE >= 4 THEN 'CHAMPION'
        WHEN R_SCORE >= 3 AND F_SCORE >= 3                  THEN 'LOYAL'
        WHEN R_SCORE <= 2 AND F_SCORE >= 3                  THEN 'AT_RISK'
        WHEN R_SCORE = 1  AND F_SCORE = 1                   THEN 'LOST'
        WHEN FREQUENCY_ORDERS = 1                           THEN 'NEW'
        ELSE 'POTENTIAL'
    END                                                          AS LIFECYCLE_SEGMENT,
    CASE
        WHEN MONETARY_TOTAL >= 5000 THEN 'HIGH'
        WHEN MONETARY_TOTAL >= 500  THEN 'MEDIUM'
        ELSE 'LOW'
    END                                                          AS VALUE_SEGMENT,
    IFF(MONETARY_TOTAL >= 5000 AND F_SCORE >= 4, TRUE, FALSE)   AS IS_VIP,
    IFF(RECENCY_DAYS > 365, TRUE, FALSE)                         AS HAS_CHURNED
FROM scored;
