-- SILVER Layer | Table: SILVER.PRODUCT_CATALOG
-- Enriched product view joining products + categories + suppliers
-- Denormalized for downstream consumption
USE SCHEMA RETAIL_DW.SILVER;

CREATE TABLE IF NOT EXISTS PRODUCT_CATALOG (
    CATALOG_SK          NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID          VARCHAR(50)   NOT NULL UNIQUE,
    SKU                 VARCHAR(100),
    PRODUCT_NAME        VARCHAR(500),
    BRAND               VARCHAR(200),
    -- Category hierarchy (pre-joined)
    CATEGORY_ID         VARCHAR(50),
    CATEGORY_NAME       VARCHAR(200),
    PARENT_CATEGORY_ID  VARCHAR(50),
    PARENT_CATEGORY_NAME VARCHAR(200),
    TOP_CATEGORY_NAME   VARCHAR(200),
    CATEGORY_PATH       VARCHAR(1000),
    -- Supplier info
    SUPPLIER_ID         VARCHAR(50),
    SUPPLIER_NAME       VARCHAR(300),
    -- Pricing
    UNIT_COST           NUMBER(18,4),
    UNIT_PRICE          NUMBER(18,4),
    MARGIN_PCT          NUMBER(8,4),  -- (price-cost)/price
    -- Status
    IS_ACTIVE           BOOLEAN,
    IS_DIGITAL          BOOLEAN,
    WEIGHT_KG           NUMBER(10,4),
    -- Timestamps
    DW_CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DW_UPDATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Full refresh: truncate and reload from normalized silver tables
TRUNCATE TABLE SILVER.PRODUCT_CATALOG;

INSERT INTO SILVER.PRODUCT_CATALOG (
    PRODUCT_ID, SKU, PRODUCT_NAME, BRAND,
    CATEGORY_ID, CATEGORY_NAME, PARENT_CATEGORY_ID, PARENT_CATEGORY_NAME, TOP_CATEGORY_NAME, CATEGORY_PATH,
    SUPPLIER_ID, SUPPLIER_NAME,
    UNIT_COST, UNIT_PRICE, MARGIN_PCT,
    IS_ACTIVE, IS_DIGITAL, WEIGHT_KG
)
SELECT
    p.PRODUCT_ID,
    p.SKU,
    p.PRODUCT_NAME,
    p.BRAND,
    c.CATEGORY_ID,
    c.CATEGORY_NAME,
    c.PARENT_CATEGORY_ID,
    pc.CATEGORY_NAME                                                              AS PARENT_CATEGORY_NAME,
    SPLIT_PART(c.CATEGORY_PATH, ' > ', 1)                                        AS TOP_CATEGORY_NAME,
    c.CATEGORY_PATH,
    s.SUPPLIER_ID,
    s.SUPPLIER_NAME,
    p.UNIT_COST,
    p.UNIT_PRICE,
    IFF(p.UNIT_PRICE > 0, (p.UNIT_PRICE - p.UNIT_COST) / p.UNIT_PRICE * 100, NULL) AS MARGIN_PCT,
    p.IS_ACTIVE,
    p.IS_DIGITAL,
    p.WEIGHT_KG
FROM SILVER.PRODUCTS p
LEFT JOIN SILVER.CATEGORIES c  ON p.CATEGORY_ID = c.CATEGORY_ID
LEFT JOIN SILVER.CATEGORIES pc ON c.PARENT_CATEGORY_ID = pc.CATEGORY_ID
LEFT JOIN SILVER.SUPPLIERS s   ON p.SUPPLIER_ID = s.SUPPLIER_ID
WHERE p.IS_CURRENT = TRUE;
