-- RAW Layer | Table: RAW.CUSTOMERS
-- Source: CRM system (Salesforce export) | Load: Full refresh daily
USE SCHEMA RETAIL_DW.RAW;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    RAW_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    SRC_CUSTOMER_ID VARCHAR(50),
    PAYLOAD         VARIANT,           -- full JSON row from source
    FILE_NAME       VARCHAR(500),
    FILE_ROW_NUMBER NUMBER,
    LOAD_TIMESTAMP  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID        VARCHAR(100)
);

-- COPY command for loading from stage
COPY INTO CUSTOMERS (SRC_CUSTOMER_ID, PAYLOAD, FILE_NAME, FILE_ROW_NUMBER, BATCH_ID)
FROM (
    SELECT
        $1::VARCHAR,
        PARSE_JSON($1),
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        '{{batch_id}}'
    FROM @CUSTOMERS_STAGE
)
FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT')
ON_ERROR = 'CONTINUE';
