-- RAW Layer | Table: RAW.ORDER_ITEMS
-- Source: OMS line items | Load: Incremental, every 15 min
USE SCHEMA RETAIL_DW.RAW;

CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    RAW_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    SRC_ORDER_ID    VARCHAR(50),
    SRC_ITEM_ID     VARCHAR(50),
    PAYLOAD         VARIANT,
    FILE_NAME       VARCHAR(500),
    FILE_ROW_NUMBER NUMBER,
    LOAD_TIMESTAMP  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID        VARCHAR(100)
);

COPY INTO ORDER_ITEMS (SRC_ORDER_ID, SRC_ITEM_ID, PAYLOAD, FILE_NAME, FILE_ROW_NUMBER, BATCH_ID)
FROM (
    SELECT
        $1:order_id::VARCHAR,
        $1:item_id::VARCHAR,
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        '{{batch_id}}'
    FROM @ORDERS_STAGE
)
FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT')
ON_ERROR = 'CONTINUE';
