-- RAW Layer | Table: RAW.CATEGORIES
-- Source: PIM system | Load: Full refresh weekly
USE SCHEMA RETAIL_DW.RAW;

CREATE TABLE IF NOT EXISTS CATEGORIES (
    RAW_ID           NUMBER AUTOINCREMENT PRIMARY KEY,
    SRC_CATEGORY_ID  VARCHAR(50),
    PAYLOAD          VARIANT,
    FILE_NAME        VARCHAR(500),
    FILE_ROW_NUMBER  NUMBER,
    LOAD_TIMESTAMP   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID         VARCHAR(100)
);

COPY INTO CATEGORIES (SRC_CATEGORY_ID, PAYLOAD, FILE_NAME, FILE_ROW_NUMBER, BATCH_ID)
FROM (
    SELECT
        $1:category_id::VARCHAR,
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        '{{batch_id}}'
    FROM @PRODUCTS_STAGE
)
FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT')
ON_ERROR = 'CONTINUE';
