-- RAW Layer | Table: RAW.SUPPLIERS
-- Source: ERP system | Load: Full refresh weekly
USE SCHEMA RETAIL_DW.RAW;

CREATE TABLE IF NOT EXISTS SUPPLIERS (
    RAW_ID           NUMBER AUTOINCREMENT PRIMARY KEY,
    SRC_SUPPLIER_ID  VARCHAR(50),
    PAYLOAD          VARIANT,
    FILE_NAME        VARCHAR(500),
    FILE_ROW_NUMBER  NUMBER,
    LOAD_TIMESTAMP   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID         VARCHAR(100)
);

COPY INTO SUPPLIERS (SRC_SUPPLIER_ID, PAYLOAD, FILE_NAME, FILE_ROW_NUMBER, BATCH_ID)
FROM (
    SELECT
        $1:supplier_id::VARCHAR,
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        '{{batch_id}}'
    FROM @INVENTORY_STAGE
)
FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FORMAT')
ON_ERROR = 'CONTINUE';
