-- RAW Layer | Table: RAW.INVENTORY
-- Source: Warehouse management system (WMS) | Load: Hourly snapshots
USE SCHEMA RETAIL_DW.RAW;

CREATE TABLE IF NOT EXISTS INVENTORY (
    RAW_ID            NUMBER AUTOINCREMENT PRIMARY KEY,
    SRC_PRODUCT_ID    VARCHAR(50),
    SRC_LOCATION_ID   VARCHAR(50),
    PAYLOAD           VARIANT,
    FILE_NAME         VARCHAR(500),
    FILE_ROW_NUMBER   NUMBER,
    LOAD_TIMESTAMP    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID          VARCHAR(100)
);

COPY INTO INVENTORY (SRC_PRODUCT_ID, SRC_LOCATION_ID, PAYLOAD, FILE_NAME, FILE_ROW_NUMBER, BATCH_ID)
FROM (
    SELECT
        $1:product_id::VARCHAR,
        $1:location_id::VARCHAR,
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        '{{batch_id}}'
    FROM @INVENTORY_STAGE
)
FILE_FORMAT = (FORMAT_NAME = 'PARQUET_FORMAT')
ON_ERROR = 'CONTINUE';
