-- RAW Layer | Table: RAW.RETURNS
-- Source: Returns management system | Load: Incremental daily
USE SCHEMA RETAIL_DW.RAW;

CREATE TABLE IF NOT EXISTS RETURNS (
    RAW_ID           NUMBER AUTOINCREMENT PRIMARY KEY,
    SRC_RETURN_ID    VARCHAR(50),
    SRC_ORDER_ID     VARCHAR(50),
    PAYLOAD          VARIANT,
    FILE_NAME        VARCHAR(500),
    FILE_ROW_NUMBER  NUMBER,
    LOAD_TIMESTAMP   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID         VARCHAR(100)
);

COPY INTO RETURNS (SRC_RETURN_ID, SRC_ORDER_ID, PAYLOAD, FILE_NAME, FILE_ROW_NUMBER, BATCH_ID)
FROM (
    SELECT
        $1:return_id::VARCHAR,
        $1:order_id::VARCHAR,
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        '{{batch_id}}'
    FROM @ORDERS_STAGE
)
FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT')
ON_ERROR = 'CONTINUE';
