-- RAW Layer | Table: RAW.EMPLOYEES
-- Source: HRIS (Workday) | Load: Full refresh daily
USE SCHEMA RETAIL_DW.RAW;

CREATE TABLE IF NOT EXISTS EMPLOYEES (
    RAW_ID            NUMBER AUTOINCREMENT PRIMARY KEY,
    SRC_EMPLOYEE_ID   VARCHAR(50),
    PAYLOAD           VARIANT,
    FILE_NAME         VARCHAR(500),
    FILE_ROW_NUMBER   NUMBER,
    LOAD_TIMESTAMP    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID          VARCHAR(100)
);

COPY INTO EMPLOYEES (SRC_EMPLOYEE_ID, PAYLOAD, FILE_NAME, FILE_ROW_NUMBER, BATCH_ID)
FROM (
    SELECT
        $1:employee_id::VARCHAR,
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        '{{batch_id}}'
    FROM @CUSTOMERS_STAGE
)
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT')
ON_ERROR = 'CONTINUE';
