-- RAW Layer | Table: RAW.PROMOTIONS
-- Source: Promotion engine | Load: Full refresh daily
USE SCHEMA RETAIL_DW.RAW;

CREATE TABLE IF NOT EXISTS PROMOTIONS (
    RAW_ID             NUMBER AUTOINCREMENT PRIMARY KEY,
    SRC_PROMOTION_ID   VARCHAR(50),
    PAYLOAD            VARIANT,
    FILE_NAME          VARCHAR(500),
    FILE_ROW_NUMBER    NUMBER,
    LOAD_TIMESTAMP     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID           VARCHAR(100)
);

COPY INTO PROMOTIONS (SRC_PROMOTION_ID, PAYLOAD, FILE_NAME, FILE_ROW_NUMBER, BATCH_ID)
FROM (
    SELECT
        $1:promotion_id::VARCHAR,
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        '{{batch_id}}'
    FROM @EVENTS_STAGE
)
FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT')
ON_ERROR = 'CONTINUE';
