-- RAW Layer | Table: RAW.WEB_SESSIONS
-- Source: Google Analytics / Segment.io | Load: Real-time via Snowpipe
USE SCHEMA RETAIL_DW.RAW;

CREATE TABLE IF NOT EXISTS WEB_SESSIONS (
    RAW_ID           NUMBER AUTOINCREMENT PRIMARY KEY,
    SRC_SESSION_ID   VARCHAR(100),
    PAYLOAD          VARIANT,
    FILE_NAME        VARCHAR(500),
    FILE_ROW_NUMBER  NUMBER,
    LOAD_TIMESTAMP   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID         VARCHAR(100)
);

CREATE PIPE IF NOT EXISTS WEB_SESSIONS_PIPE
    AUTO_INGEST = TRUE
    COMMENT = 'Auto-ingest clickstream events from S3'
AS
COPY INTO WEB_SESSIONS (SRC_SESSION_ID, PAYLOAD, FILE_NAME, FILE_ROW_NUMBER)
FROM (
    SELECT
        $1:session_id::VARCHAR,
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @EVENTS_STAGE
)
FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');
