-- RAW Layer | Table: RAW.PAGE_VIEWS
-- Source: Clickstream (Segment.io) | Load: Real-time via Snowpipe
USE SCHEMA RETAIL_DW.RAW;

CREATE TABLE IF NOT EXISTS PAGE_VIEWS (
    RAW_ID           NUMBER AUTOINCREMENT PRIMARY KEY,
    SRC_SESSION_ID   VARCHAR(100),
    SRC_PAGE_URL     VARCHAR(2000),
    PAYLOAD          VARIANT,
    FILE_NAME        VARCHAR(500),
    FILE_ROW_NUMBER  NUMBER,
    LOAD_TIMESTAMP   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID         VARCHAR(100)
);

CREATE PIPE IF NOT EXISTS PAGE_VIEWS_PIPE
    AUTO_INGEST = TRUE
    COMMENT = 'Auto-ingest page view events'
AS
COPY INTO PAGE_VIEWS (SRC_SESSION_ID, SRC_PAGE_URL, PAYLOAD, FILE_NAME, FILE_ROW_NUMBER)
FROM (
    SELECT
        $1:session_id::VARCHAR,
        $1:page_url::VARCHAR,
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @EVENTS_STAGE
)
FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');
