-- RAW Layer | Table: RAW.SHIPMENTS
-- Source: Logistics / carrier APIs (FedEx, UPS, DHL) | Load: Hourly
USE SCHEMA RETAIL_DW.RAW;

CREATE TABLE IF NOT EXISTS SHIPMENTS (
    RAW_ID             NUMBER AUTOINCREMENT PRIMARY KEY,
    SRC_SHIPMENT_ID    VARCHAR(50),
    SRC_ORDER_ID       VARCHAR(50),
    PAYLOAD            VARIANT,
    FILE_NAME          VARCHAR(500),
    FILE_ROW_NUMBER    NUMBER,
    LOAD_TIMESTAMP     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID           VARCHAR(100)
);

COPY INTO SHIPMENTS (SRC_SHIPMENT_ID, SRC_ORDER_ID, PAYLOAD, FILE_NAME, FILE_ROW_NUMBER, BATCH_ID)
FROM (
    SELECT
        $1:shipment_id::VARCHAR,
        $1:order_id::VARCHAR,
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        '{{batch_id}}'
    FROM @ORDERS_STAGE
)
FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT')
ON_ERROR = 'CONTINUE';
