-- RAW Layer | Table: RAW.ADDRESSES
-- Source: CRM / OMS | Load: Incremental daily
USE SCHEMA RETAIL_DW.RAW;

CREATE TABLE IF NOT EXISTS ADDRESSES (
    RAW_ID           NUMBER AUTOINCREMENT PRIMARY KEY,
    SRC_ADDRESS_ID   VARCHAR(50),
    SRC_CUSTOMER_ID  VARCHAR(50),
    PAYLOAD          VARIANT,
    FILE_NAME        VARCHAR(500),
    FILE_ROW_NUMBER  NUMBER,
    LOAD_TIMESTAMP   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID         VARCHAR(100)
);

COPY INTO ADDRESSES (SRC_ADDRESS_ID, SRC_CUSTOMER_ID, PAYLOAD, FILE_NAME, FILE_ROW_NUMBER, BATCH_ID)
FROM (
    SELECT
        $1:address_id::VARCHAR,
        $1:customer_id::VARCHAR,
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        '{{batch_id}}'
    FROM @CUSTOMERS_STAGE
)
FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT')
ON_ERROR = 'CONTINUE';
