-- GOLD Layer | Dimension: GOLD.DIM_STORES
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE DIM_STORES AS
SELECT
    STORE_SK,
    STORE_ID,
    STORE_NAME,
    STORE_TYPE,
    ADDRESS_LINE1,
    CITY,
    STATE_PROVINCE,
    POSTAL_CODE,
    COUNTRY_CODE,
    LATITUDE,
    LONGITUDE,
    TIMEZONE,
    OPENING_DATE,
    CLOSING_DATE,
    IS_ACTIVE,
    STORE_MANAGER_ID,
    SQUARE_FOOTAGE,
    -- Derived
    DATEDIFF('year', OPENING_DATE, CURRENT_DATE())            AS YEARS_OPEN,
    IFF(SQUARE_FOOTAGE >= 10000, 'LARGE', IFF(SQUARE_FOOTAGE >= 3000, 'MEDIUM', 'SMALL')) AS SIZE_CATEGORY,
    CURRENT_TIMESTAMP()                                       AS DW_REFRESHED_AT
FROM SILVER.STORES;
