-- GOLD Layer | Dimension: GOLD.DIM_EMPLOYEES
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE DIM_EMPLOYEES AS
SELECT
    EMPLOYEE_SK,
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    FULL_NAME,
    JOB_TITLE,
    DEPARTMENT,
    STORE_ID,
    MANAGER_ID,
    HIRE_DATE,
    TERMINATION_DATE,
    EMPLOYMENT_STATUS,
    EMPLOYMENT_TYPE,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    IS_CURRENT,
    DATEDIFF('year', HIRE_DATE, COALESCE(TERMINATION_DATE, CURRENT_DATE())) AS TENURE_YEARS,
    CURRENT_TIMESTAMP()                                                     AS DW_REFRESHED_AT
FROM SILVER.EMPLOYEES;
