-- GOLD Layer | Dimension: GOLD.DIM_SUPPLIERS
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE DIM_SUPPLIERS AS
SELECT
    SUPPLIER_SK,
    SUPPLIER_ID,
    SUPPLIER_NAME,
    CONTACT_NAME,
    EMAIL,
    PHONE,
    COUNTRY,
    REGION,
    PAYMENT_TERMS_DAYS,
    LEAD_TIME_DAYS,
    IS_ACTIVE,
    SUPPLIER_RATING,
    CASE
        WHEN SUPPLIER_RATING >= 4.5 THEN 'PREFERRED'
        WHEN SUPPLIER_RATING >= 3.5 THEN 'APPROVED'
        WHEN SUPPLIER_RATING >= 2.5 THEN 'CONDITIONAL'
        ELSE 'PROBATION'
    END                        AS SUPPLIER_STATUS_LABEL,
    CURRENT_TIMESTAMP()        AS DW_REFRESHED_AT
FROM SILVER.SUPPLIERS;
