-- GOLD Layer | Dimension: GOLD.DIM_PROMOTIONS
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE DIM_PROMOTIONS AS
SELECT
    PROMOTION_SK,
    PROMOTION_ID,
    PROMOTION_NAME,
    PROMOTION_TYPE,
    DISCOUNT_VALUE,
    MIN_ORDER_AMOUNT,
    MAX_DISCOUNT_AMOUNT,
    START_DATE,
    END_DATE,
    APPLIES_TO,
    PROMO_CODE,
    IS_STACKABLE,
    IS_ACTIVE,
    USAGE_LIMIT,
    TIMES_USED,
    DATEDIFF('day', START_DATE, END_DATE)   AS DURATION_DAYS,
    IFF(USAGE_LIMIT > 0, TIMES_USED / USAGE_LIMIT * 100, NULL) AS USAGE_RATE_PCT,
    CURRENT_TIMESTAMP()                     AS DW_REFRESHED_AT
FROM SILVER.PROMOTIONS;
