-- GOLD Layer | Dimension: GOLD.DIM_CATEGORIES
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE DIM_CATEGORIES AS
SELECT
    c.CATEGORY_SK,
    c.CATEGORY_ID,
    c.CATEGORY_NAME,
    c.PARENT_CATEGORY_ID,
    p.CATEGORY_NAME     AS PARENT_CATEGORY_NAME,
    c.CATEGORY_LEVEL,
    c.CATEGORY_PATH,
    c.IS_ACTIVE,
    CURRENT_TIMESTAMP() AS DW_REFRESHED_AT
FROM SILVER.CATEGORIES c
LEFT JOIN SILVER.CATEGORIES p ON c.PARENT_CATEGORY_ID = p.CATEGORY_ID;
