-- GOLD Layer | Dimension: GOLD.DIM_ADDRESSES
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE DIM_ADDRESSES AS
SELECT
    ADDRESS_SK,
    ADDRESS_ID,
    CUSTOMER_ID,
    ADDRESS_TYPE,
    ADDRESS_LINE1,
    ADDRESS_LINE2,
    CITY,
    STATE_PROVINCE,
    POSTAL_CODE,
    COUNTRY_CODE,
    IS_DEFAULT,
    IS_VALIDATED,
    LATITUDE,
    LONGITUDE,
    IS_CURRENT,
    CURRENT_TIMESTAMP() AS DW_REFRESHED_AT
FROM SILVER.ADDRESSES
WHERE IS_CURRENT = TRUE;
