-- GOLD Layer | Dimension: GOLD.DIM_CAMPAIGNS
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE DIM_CAMPAIGNS AS
SELECT
    CAMPAIGN_SK,
    CAMPAIGN_ID,
    CAMPAIGN_NAME,
    CAMPAIGN_TYPE,
    CHANNEL,
    START_DATE,
    END_DATE,
    BUDGET_AMOUNT,
    SPEND_AMOUNT,
    TARGET_AUDIENCE,
    IMPRESSIONS,
    CLICKS,
    CONVERSIONS,
    REVENUE_ATTRIBUTED,
    IS_ACTIVE,
    DATEDIFF('day', START_DATE, END_DATE)               AS CAMPAIGN_DURATION_DAYS,
    IFF(IMPRESSIONS > 0, CLICKS / IMPRESSIONS * 100, NULL)        AS CTR_PCT,
    IFF(CLICKS > 0, CONVERSIONS / CLICKS * 100, NULL)             AS CONVERSION_RATE_PCT,
    IFF(CONVERSIONS > 0, SPEND_AMOUNT / CONVERSIONS, NULL)        AS COST_PER_CONVERSION,
    IFF(SPEND_AMOUNT > 0, (REVENUE_ATTRIBUTED - SPEND_AMOUNT) / SPEND_AMOUNT * 100, NULL) AS ROAS_PCT,
    CURRENT_TIMESTAMP()                                 AS DW_REFRESHED_AT
FROM SILVER.CAMPAIGNS;
