-- GOLD Mart | GOLD.DAILY_SALES_SUMMARY
-- Pre-aggregated daily sales KPIs for BI dashboards
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE DAILY_SALES_SUMMARY AS
SELECT
    d.FULL_DATE                                          AS SALE_DATE,
    d.YEAR_NUMBER,
    d.QUARTER_NAME,
    d.MONTH_NAME,
    d.WEEK_OF_YEAR,
    d.IS_WEEKEND,
    d.IS_HOLIDAY,
    COUNT(DISTINCT fs.ORDER_ID)                          AS TOTAL_ORDERS,
    COUNT(DISTINCT fs.CUSTOMER_ID)                       AS UNIQUE_CUSTOMERS,
    COUNT(DISTINCT IFF(fs.IS_FIRST_ORDER, fs.CUSTOMER_ID, NULL)) AS NEW_CUSTOMERS,
    SUM(fs.TOTAL_AMOUNT)                                 AS GROSS_REVENUE,
    SUM(fs.DISCOUNT_AMOUNT)                              AS TOTAL_DISCOUNTS,
    SUM(fs.TAX_AMOUNT)                                   AS TOTAL_TAX,
    SUM(fs.SHIPPING_AMOUNT)                              AS TOTAL_SHIPPING,
    SUM(fs.NET_REVENUE)                                  AS NET_REVENUE,
    AVG(fs.TOTAL_AMOUNT)                                 AS AVG_ORDER_VALUE,
    SUM(fs.TOTAL_AMOUNT) / NULLIF(COUNT(DISTINCT fs.CUSTOMER_ID), 0) AS REVENUE_PER_CUSTOMER,
    COUNT(DISTINCT IFF(fs.PROMOTION_ID IS NOT NULL, fs.ORDER_ID, NULL)) AS PROMO_ORDERS,
    SUM(IFF(fs.PROMOTION_ID IS NOT NULL, fs.DISCOUNT_AMOUNT, 0))        AS PROMO_DISCOUNT_AMOUNT,
    -- DoD comparison
    LAG(SUM(fs.TOTAL_AMOUNT)) OVER (ORDER BY d.FULL_DATE)  AS PREV_DAY_REVENUE,
    SUM(fs.TOTAL_AMOUNT) - LAG(SUM(fs.TOTAL_AMOUNT)) OVER (ORDER BY d.FULL_DATE) AS REVENUE_DOD_CHANGE,
    -- 7-day rolling
    AVG(SUM(fs.TOTAL_AMOUNT)) OVER (ORDER BY d.FULL_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS REVENUE_7D_ROLLING_AVG,
    -- 28-day rolling
    AVG(SUM(fs.TOTAL_AMOUNT)) OVER (ORDER BY d.FULL_DATE ROWS BETWEEN 27 PRECEDING AND CURRENT ROW) AS REVENUE_28D_ROLLING_AVG,
    CURRENT_TIMESTAMP()                                  AS DW_REFRESHED_AT
FROM GOLD.FACT_SALES fs
JOIN GOLD.DIM_DATE d ON fs.DATE_SK = d.DATE_SK
GROUP BY d.FULL_DATE, d.YEAR_NUMBER, d.QUARTER_NAME, d.MONTH_NAME, d.WEEK_OF_YEAR, d.IS_WEEKEND, d.IS_HOLIDAY;
