-- GOLD Mart | GOLD.MONTHLY_REVENUE
-- Monthly revenue aggregates with MoM and YoY comparisons
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE MONTHLY_REVENUE AS
WITH monthly AS (
    SELECT
        d.YEAR_NUMBER,
        d.MONTH_NUMBER,
        d.MONTH_NAME,
        d.MONTH_START_DATE,
        d.MONTH_END_DATE,
        d.FISCAL_YEAR,
        d.FISCAL_MONTH,
        COUNT(DISTINCT fs.ORDER_ID)                AS ORDERS,
        COUNT(DISTINCT fs.CUSTOMER_ID)             AS CUSTOMERS,
        SUM(fs.TOTAL_AMOUNT)                       AS GROSS_REVENUE,
        SUM(fs.NET_REVENUE)                        AS NET_REVENUE,
        SUM(fs.DISCOUNT_AMOUNT)                    AS DISCOUNTS,
        SUM(fs.TAX_AMOUNT)                         AS TAX,
        SUM(fs.SHIPPING_AMOUNT)                    AS SHIPPING_REVENUE,
        AVG(fs.TOTAL_AMOUNT)                       AS AOV,
        COUNT(DISTINCT fs.STORE_ID)                AS ACTIVE_STORES
    FROM GOLD.FACT_SALES fs
    JOIN GOLD.DIM_DATE d ON fs.DATE_SK = d.DATE_SK
    GROUP BY d.YEAR_NUMBER, d.MONTH_NUMBER, d.MONTH_NAME, d.MONTH_START_DATE, d.MONTH_END_DATE, d.FISCAL_YEAR, d.FISCAL_MONTH
)
SELECT
    *,
    LAG(GROSS_REVENUE) OVER (ORDER BY YEAR_NUMBER, MONTH_NUMBER)                    AS PREV_MONTH_REVENUE,
    GROSS_REVENUE - LAG(GROSS_REVENUE) OVER (ORDER BY YEAR_NUMBER, MONTH_NUMBER)    AS REVENUE_MOM_CHANGE,
    IFF(LAG(GROSS_REVENUE) OVER (ORDER BY YEAR_NUMBER, MONTH_NUMBER) > 0,
        (GROSS_REVENUE - LAG(GROSS_REVENUE) OVER (ORDER BY YEAR_NUMBER, MONTH_NUMBER))
            / LAG(GROSS_REVENUE) OVER (ORDER BY YEAR_NUMBER, MONTH_NUMBER) * 100,
        NULL)                                                                        AS REVENUE_MOM_PCT,
    LAG(GROSS_REVENUE, 12) OVER (ORDER BY YEAR_NUMBER, MONTH_NUMBER)               AS SAME_MONTH_LY_REVENUE,
    IFF(LAG(GROSS_REVENUE, 12) OVER (ORDER BY YEAR_NUMBER, MONTH_NUMBER) > 0,
        (GROSS_REVENUE - LAG(GROSS_REVENUE, 12) OVER (ORDER BY YEAR_NUMBER, MONTH_NUMBER))
            / LAG(GROSS_REVENUE, 12) OVER (ORDER BY YEAR_NUMBER, MONTH_NUMBER) * 100,
        NULL)                                                                        AS REVENUE_YOY_PCT,
    SUM(GROSS_REVENUE) OVER (PARTITION BY YEAR_NUMBER ORDER BY MONTH_NUMBER)        AS YTD_REVENUE,
    CURRENT_TIMESTAMP()                                                              AS DW_REFRESHED_AT
FROM monthly;
