-- GOLD Mart | GOLD.STORE_PERFORMANCE_MONTHLY
-- Monthly KPIs per store including comparable store sales
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE STORE_PERFORMANCE_MONTHLY AS
WITH monthly_store AS (
    SELECT
        s.STORE_ID,
        s.STORE_NAME,
        s.STORE_TYPE,
        s.CITY,
        s.STATE_PROVINCE,
        s.COUNTRY_CODE,
        s.SQUARE_FOOTAGE,
        d.YEAR_NUMBER,
        d.MONTH_NUMBER,
        d.MONTH_NAME,
        d.MONTH_START_DATE,
        COUNT(DISTINCT fs.ORDER_ID)                AS ORDERS,
        COUNT(DISTINCT fs.CUSTOMER_ID)             AS UNIQUE_CUSTOMERS,
        SUM(fs.TOTAL_AMOUNT)                       AS GROSS_REVENUE,
        SUM(fs.NET_REVENUE)                        AS NET_REVENUE,
        SUM(fs.DISCOUNT_AMOUNT)                    AS DISCOUNTS,
        AVG(fs.TOTAL_AMOUNT)                       AS AOV,
        COUNT(DISTINCT IFF(fs.IS_FIRST_ORDER, fs.CUSTOMER_ID, NULL)) AS NEW_CUSTOMERS,
        SUM(fs.TOTAL_AMOUNT) / NULLIF(s.SQUARE_FOOTAGE, 0)           AS REVENUE_PER_SQFT
    FROM GOLD.FACT_SALES fs
    JOIN GOLD.DIM_STORES  s ON fs.STORE_SK = s.STORE_SK
    JOIN GOLD.DIM_DATE    d ON fs.DATE_SK  = d.DATE_SK
    GROUP BY s.STORE_ID, s.STORE_NAME, s.STORE_TYPE, s.CITY, s.STATE_PROVINCE,
             s.COUNTRY_CODE, s.SQUARE_FOOTAGE, d.YEAR_NUMBER, d.MONTH_NUMBER, d.MONTH_NAME, d.MONTH_START_DATE
)
SELECT
    *,
    LAG(GROSS_REVENUE) OVER (PARTITION BY STORE_ID ORDER BY YEAR_NUMBER, MONTH_NUMBER) AS PREV_MONTH_REVENUE,
    IFF(LAG(GROSS_REVENUE) OVER (PARTITION BY STORE_ID ORDER BY YEAR_NUMBER, MONTH_NUMBER) > 0,
        (GROSS_REVENUE - LAG(GROSS_REVENUE) OVER (PARTITION BY STORE_ID ORDER BY YEAR_NUMBER, MONTH_NUMBER))
            / LAG(GROSS_REVENUE) OVER (PARTITION BY STORE_ID ORDER BY YEAR_NUMBER, MONTH_NUMBER) * 100,
        NULL) AS MOM_GROWTH_PCT,
    LAG(GROSS_REVENUE, 12) OVER (PARTITION BY STORE_ID ORDER BY YEAR_NUMBER, MONTH_NUMBER) AS SAME_MONTH_LY,
    IFF(LAG(GROSS_REVENUE, 12) OVER (PARTITION BY STORE_ID ORDER BY YEAR_NUMBER, MONTH_NUMBER) > 0,
        (GROSS_REVENUE - LAG(GROSS_REVENUE, 12) OVER (PARTITION BY STORE_ID ORDER BY YEAR_NUMBER, MONTH_NUMBER))
            / LAG(GROSS_REVENUE, 12) OVER (PARTITION BY STORE_ID ORDER BY YEAR_NUMBER, MONTH_NUMBER) * 100,
        NULL) AS YOY_GROWTH_PCT,
    RANK() OVER (PARTITION BY YEAR_NUMBER, MONTH_NUMBER ORDER BY GROSS_REVENUE DESC) AS REVENUE_RANK_IN_PERIOD,
    CURRENT_TIMESTAMP() AS DW_REFRESHED_AT
FROM monthly_store;
