-- GOLD Mart | GOLD.TOP_CUSTOMERS
-- Ranked customer leaderboard with segment context
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE TOP_CUSTOMERS AS
SELECT
    clv.CUSTOMER_SK,
    clv.CUSTOMER_ID,
    clv.FULL_NAME,
    clv.CUSTOMER_TIER,
    clv.CLV_TIER,
    clv.CHURN_RISK,
    clv.FIRST_ORDER_DATE,
    clv.LAST_ORDER_DATE,
    clv.TOTAL_ORDERS,
    clv.LIFETIME_REVENUE,
    clv.NET_LIFETIME_REVENUE,
    clv.AVG_ORDER_VALUE,
    clv.ORDERS_PER_YEAR,
    clv.PROJECTED_CLV_3YR,
    clv.TOTAL_RETURNS,
    clv.TOTAL_REFUNDS,
    clv.DAYS_SINCE_LAST_ORDER,
    seg.LIFECYCLE_SEGMENT,
    seg.RFM_COMBINED_SCORE,
    seg.IS_VIP,
    -- Rankings
    RANK() OVER (ORDER BY clv.LIFETIME_REVENUE DESC)     AS REVENUE_RANK,
    RANK() OVER (ORDER BY clv.TOTAL_ORDERS DESC)         AS ORDER_FREQUENCY_RANK,
    RANK() OVER (ORDER BY clv.PROJECTED_CLV_3YR DESC)    AS CLV_RANK,
    NTILE(10) OVER (ORDER BY clv.LIFETIME_REVENUE DESC)  AS REVENUE_DECILE,  -- 1=top 10%
    CURRENT_TIMESTAMP()                                  AS DW_REFRESHED_AT
FROM GOLD.CUSTOMER_LIFETIME_VALUE clv
LEFT JOIN SILVER.CUSTOMER_SEGMENTS seg
    ON clv.CUSTOMER_ID = seg.CUSTOMER_ID AND seg.SEGMENT_DATE = CURRENT_DATE()
ORDER BY clv.LIFETIME_REVENUE DESC;
