-- GOLD Mart | GOLD.RETURN_RATE_ANALYSIS
-- Return rates sliced by product, category, customer segment, and time
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE TABLE RETURN_RATE_ANALYSIS AS
SELECT
    d.YEAR_NUMBER,
    d.QUARTER_NAME,
    d.MONTH_NAME,
    p.CATEGORY_NAME,
    p.TOP_CATEGORY_NAME,
    p.BRAND,
    r.RETURN_REASON,
    -- Volume
    COUNT(DISTINCT r.RETURN_ID)                            AS TOTAL_RETURNS,
    COUNT(DISTINCT fs.ORDER_ID)                            AS TOTAL_ORDERS_IN_PERIOD,
    SUM(r.REFUND_AMOUNT)                                   AS TOTAL_REFUND_AMOUNT,
    -- Rates
    COUNT(DISTINCT r.RETURN_ID) /
        NULLIF(COUNT(DISTINCT fs.ORDER_ID), 0) * 100      AS ORDER_RETURN_RATE_PCT,
    SUM(r.REFUND_AMOUNT) /
        NULLIF(SUM(fs.TOTAL_AMOUNT), 0) * 100             AS REVENUE_RETURN_RATE_PCT,
    -- Timing
    AVG(DATEDIFF('day', fs.ORDER_DATE, r.RETURN_DATE))    AS AVG_DAYS_TO_RETURN,
    -- Refund method breakdown
    SUM(IFF(r.REFUND_METHOD = 'ORIGINAL_PAYMENT', r.REFUND_AMOUNT, 0)) AS REFUNDED_TO_CARD,
    SUM(IFF(r.REFUND_METHOD = 'STORE_CREDIT', r.REFUND_AMOUNT, 0))     AS REFUNDED_AS_CREDIT,
    CURRENT_TIMESTAMP()                                   AS DW_REFRESHED_AT
FROM GOLD.FACT_RETURNS r
JOIN GOLD.FACT_SALES     fs  ON r.ORDER_SK  = fs.ORDER_SK
JOIN GOLD.DIM_DATE       d   ON fs.DATE_SK  = d.DATE_SK
JOIN GOLD.FACT_ORDER_ITEMS foi ON r.ORDER_ID = foi.ORDER_ID
JOIN GOLD.DIM_PRODUCTS   p   ON foi.PRODUCT_ID = p.PRODUCT_ID
GROUP BY d.YEAR_NUMBER, d.QUARTER_NAME, d.MONTH_NAME, p.CATEGORY_NAME, p.TOP_CATEGORY_NAME, p.BRAND, r.RETURN_REASON;
