-- GOLD Mart | View: GOLD.CUSTOMER_LOYALTY_SUMMARY
-- Aggregates loyalty activity per customer for BI dashboards and CRM exports
USE SCHEMA RETAIL_DW.GOLD;

CREATE OR REPLACE VIEW CUSTOMER_LOYALTY_SUMMARY AS
SELECT
    c.CUSTOMER_SK,
    c.CUSTOMER_ID,
    c.FULL_NAME,
    c.EMAIL,
    c.CUSTOMER_TIER,
    c.LOYALTY_SCORE,
    c.LOYALTY_TIER,
    -- Points activity
    lp.TOTAL_POINTS_EARNED,
    lp.TOTAL_POINTS_REDEEMED,
    lp.TOTAL_POINTS_EARNED - lp.TOTAL_POINTS_REDEEMED    AS POINTS_BALANCE,
    lp.LAST_EARN_DATE,
    lp.LAST_REDEEM_DATE,
    -- Engagement signals
    DATEDIFF('day', lp.LAST_EARN_DATE, CURRENT_DATE())   AS DAYS_SINCE_LAST_EARN,
    CASE
        WHEN DATEDIFF('day', lp.LAST_EARN_DATE, CURRENT_DATE()) <= 30  THEN 'ACTIVE'
        WHEN DATEDIFF('day', lp.LAST_EARN_DATE, CURRENT_DATE()) <= 90  THEN 'AT_RISK'
        ELSE 'LAPSED'
    END                                                   AS LOYALTY_ENGAGEMENT_STATUS,
    -- Lifetime value proxy
    fs.TOTAL_ORDER_VALUE,
    fs.ORDER_COUNT,
    ROUND(fs.TOTAL_ORDER_VALUE / NULLIF(fs.ORDER_COUNT, 0), 2) AS AVG_ORDER_VALUE,
    CURRENT_TIMESTAMP()                                   AS DW_REFRESHED_AT
FROM DIM_CUSTOMERS c
LEFT JOIN (
    SELECT
        CUSTOMER_ID,
        SUM(POINTS_EARNED)    AS TOTAL_POINTS_EARNED,
        SUM(POINTS_REDEEMED)  AS TOTAL_POINTS_REDEEMED,
        MAX(TRANSACTION_DATE) AS LAST_EARN_DATE,
        MAX(CASE WHEN POINTS_REDEEMED > 0 THEN TRANSACTION_DATE END) AS LAST_REDEEM_DATE
    FROM SILVER.LOYALTY_TRANSACTIONS
    GROUP BY CUSTOMER_ID
) lp ON c.CUSTOMER_ID = lp.CUSTOMER_ID
LEFT JOIN (
    SELECT
        CUSTOMER_SK,
        SUM(TOTAL_AMOUNT)   AS TOTAL_ORDER_VALUE,
        COUNT(DISTINCT ORDER_SK) AS ORDER_COUNT
    FROM FACT_SALES
    GROUP BY CUSTOMER_SK
) fs ON c.CUSTOMER_SK = fs.CUSTOMER_SK
WHERE c.IS_CURRENT = TRUE;
