-- ============================================================
-- Snowflake Retail Data Warehouse - Initialization
-- Database: RETAIL_DW | Architecture: Medallion (Raw/Silver/Gold)
-- ============================================================

USE ROLE SYSADMIN;

-- Warehouses
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WITH WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'General ETL compute warehouse';

CREATE WAREHOUSE IF NOT EXISTS REPORTING_WH
    WITH WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'BI and reporting warehouse';

-- Database
CREATE DATABASE IF NOT EXISTS RETAIL_DW
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Retail e-commerce data warehouse - medallion architecture';

-- Schemas
CREATE SCHEMA IF NOT EXISTS RETAIL_DW.RAW
    DATA_RETENTION_TIME_IN_DAYS = 3
    COMMENT = 'Raw ingestion layer - source data as-is with metadata';

CREATE SCHEMA IF NOT EXISTS RETAIL_DW.SILVER
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Silver layer - cleaned, typed, deduplicated, conformed';

CREATE SCHEMA IF NOT EXISTS RETAIL_DW.GOLD
    DATA_RETENTION_TIME_IN_DAYS = 14
    COMMENT = 'Gold layer - business-ready dimensions, facts, and marts';

USE DATABASE RETAIL_DW;
USE SCHEMA RAW;

-- File Formats
CREATE FILE FORMAT IF NOT EXISTS RAW.JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = TRUE
    IGNORE_UTF8_ERRORS = TRUE
    NULL_IF = ('', 'null', 'NULL');

CREATE FILE FORMAT IF NOT EXISTS RAW.CSV_FORMAT
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL', 'N/A');

CREATE FILE FORMAT IF NOT EXISTS RAW.PARQUET_FORMAT
    TYPE = 'PARQUET'
    SNAPPY_COMPRESSION = TRUE;

-- Internal Stages
CREATE STAGE IF NOT EXISTS RAW.CUSTOMERS_STAGE      FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_FORMAT');
CREATE STAGE IF NOT EXISTS RAW.ORDERS_STAGE         FILE_FORMAT = (FORMAT_NAME = 'RAW.JSON_FORMAT');
CREATE STAGE IF NOT EXISTS RAW.PRODUCTS_STAGE       FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_FORMAT');
CREATE STAGE IF NOT EXISTS RAW.EVENTS_STAGE         FILE_FORMAT = (FORMAT_NAME = 'RAW.JSON_FORMAT');
CREATE STAGE IF NOT EXISTS RAW.INVENTORY_STAGE      FILE_FORMAT = (FORMAT_NAME = 'RAW.PARQUET_FORMAT');

-- Roles
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS RAW_LOADER      COMMENT = 'Loads data into raw layer';
CREATE ROLE IF NOT EXISTS SILVER_TRANSFORMER COMMENT = 'Transforms raw to silver';
CREATE ROLE IF NOT EXISTS GOLD_ANALYST    COMMENT = 'Reads from gold layer';
CREATE ROLE IF NOT EXISTS DW_ADMIN        COMMENT = 'Full data warehouse access';

GRANT ROLE RAW_LOADER        TO ROLE DW_ADMIN;
GRANT ROLE SILVER_TRANSFORMER TO ROLE DW_ADMIN;
GRANT ROLE GOLD_ANALYST       TO ROLE DW_ADMIN;
GRANT ROLE DW_ADMIN           TO ROLE SYSADMIN;

-- Schema privileges
USE ROLE SYSADMIN;
GRANT USAGE ON DATABASE RETAIL_DW TO ROLE RAW_LOADER;
GRANT USAGE, CREATE TABLE, CREATE STAGE ON SCHEMA RETAIL_DW.RAW TO ROLE RAW_LOADER;

GRANT USAGE ON DATABASE RETAIL_DW TO ROLE SILVER_TRANSFORMER;
GRANT USAGE ON SCHEMA RETAIL_DW.RAW    TO ROLE SILVER_TRANSFORMER;
GRANT USAGE, CREATE TABLE ON SCHEMA RETAIL_DW.SILVER TO ROLE SILVER_TRANSFORMER;

GRANT USAGE ON DATABASE RETAIL_DW TO ROLE GOLD_ANALYST;
GRANT USAGE ON SCHEMA RETAIL_DW.SILVER TO ROLE GOLD_ANALYST;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA RETAIL_DW.GOLD TO ROLE GOLD_ANALYST;

GRANT USAGE ON WAREHOUSE COMPUTE_WH  TO ROLE RAW_LOADER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH  TO ROLE SILVER_TRANSFORMER;
GRANT USAGE ON WAREHOUSE REPORTING_WH TO ROLE GOLD_ANALYST;
